src/gear2/tags.nim

ref https://github.com/nim-lang/Nim/pull/23892
ref https://github.com/nim-lang/Nim/pull/24018

fixes for latest compiler changes

---

doc/nifc-spec.md
src/nifc/gentypes.nim

bug fixes for number types

---

src/nifc/nifc.nim

ref #52; allows nifc to take multiple files in order

---

src/nifc/codegen.nim
src/nifc/genexprs.nim
src/nifc/genstmts.nim
tests/nifc/issues.nif

supersedes https://github.com/nim-lang/nif/pull/70

implements #line generators

---

.github/workflows/ci.yml
src/nifc/bat.nim
src/nifc/nifc.nim
src/nifc/noptions.nim

I will refactor them in the next PR

implements `.bat` support on Windows

---

src/gear3/expander.nim
src/lib/keymatcher.nim
src/lib/nifcursors.nim
src/lib/nifindexes.nim
src/lib/nifstreams.nim
src/lib/symparser.nim
src/nimony/decls.nim
src/nimony/magics.nim
src/nimony/nifconfig.nim
src/nimony/nim.cfg
src/nimony/nimony.nim
src/nimony/nimony_model.nim
src/nimony/programs.nim
src/nimony/reporters.nim
src/nimony/sem.nim
src/nimony/sigmatch.nim
src/nimony/symtabs.nim

Nimony progress

---

src/gear3/expander.nim
src/nifc/codegen.nim
src/nifc/genstmts.nim
tests/gear3/gear3_helloworld.nif
tests/gear3/mod1.nif

improves gear3

---

src/gear3/expander.nim
src/lib/nifcursors.nim
src/lib/nifstreams.nim
src/nimony/programs.nim
src/nimony/sem.nim
src/nimony/sigmatch.nim

Nimony: progress

---

src/nimony/nimony_model.nim

corrects `IterS`

---

src/nimony/magics.nim

nimony: add typedesc tag to magics

---

src/gear3/expander.nim

gear3: implements `TupleT`

---

src/nifler/bridge.nim
src/nimony/sem.nim
src/nimony/tests/basics/t1.nim

nimony: fixes tuple types

---

src/nimony/sem.nim
src/nimony/tests/basics/t1.nim

`semStmtBranch` should also work for `case`/`try` as well

nimony: `if` expressions, make commonType work with noreturn

---

src/nimony/sem.nim

These would be useful for `typedesc` arguments, though the vast majority of typedesc arguments are either symbols or generic invocations.

nimony: allow structural types as expressions

---

src/nifler/bridge.nim

`n[n.len-2].kind` of an object type is `nkOfInherit`

nifler: fixes parsing inherited object types

---

src/gear3/expander.nim
tests/gear3/gear3_helloworld.nif

converts `(eq Type Expr Expr)` to `(eq Expr Expr)`

gear3: fixes EqX, NeqX, LeX, LtX

---

src/nimony/sem.nim

As mentioned in https://github.com/nim-lang/nif/pull/182#issuecomment-2530638253.

nimony: turn type symbols into type AST for non-nominal types

---

src/nimony/sem.nim
src/nimony/tests/basics/t1.nim

nimony: support tuple fields in dot

---

src/gear3/expander.nim
src/nimony/nimony_model.nim
src/nimony/semborrow.nim
tests/nimony/basics/tdistinct.nif

closes #236
adds a `ret` when it's a call expression

maps borrow to InlineC and fixes borrows

---

src/gear3/expander.nim
src/nimony/nimony_model.nim
src/nimony/programs.nim
src/nimony/sem.nim
tests/nimony/basics/deps/mdeclared.nim
tests/nimony/basics/deps/modexcept.nim
tests/nimony/basics/deps/modfrom.nim
tests/nimony/basics/timportfromexcept.nif
tests/nimony/basics/timportfromexcept.nim

My best attempt at good enough looking code, open to suggestions

implement `from import`/`import except`, fix declared

---

src/nimony/sem.nim
tests/nimony/basics/t1.nim

closes #267
Does not check if every field was assigned/insert default values etc. Assuming this is enough for now

nimony: basic object constructors

---

src/gear3/expander.nim
tests/gear3/gear3_helloworld.nif

gear3: fixes object constructors

---

src/nimony/sem.nim
tests/nimony/basics/ttemplate.nif
tests/nimony/basics/ttemplate.nim

Currently has the exact same behavior as a fresh conversion call

semcheck conv nodes

---

src/gear3/expander.nim
src/nimony/decls.nim
src/nimony/nimony_model.nim
src/nimony/sem.nim
src/nimony/sigmatch.nim
src/nimony/typeprops.nim
tests/nimony/basics/tholeyenum.msgs
tests/nimony/basics/tholeyenum.nim

closes #292
Can change the name

dedicate tag to holey enums

---

src/nimony/sem.nim
src/nimony/typeprops.nim
tests/nimony/sysbasics/tdefault.nif

Partially already in #299 but just in case splitting it helps

fix bugs with low/high and object constructors

---

src/nimony/sem.nim
src/nimony/xints.nim
tests/nimony/basics/tbool.nif
tests/nimony/basics/tenumsizes.nif
tests/nimony/basics/tenumsizes.nim
tests/nimony/sysbasics/tdefault.nif
tests/nimony/sysbasics/tdollar.nif

set enum base types in sem

---

lib/std/system.nim
src/gear3/expander.nim
src/gear3/typenav.nim
src/nimony/magics.nim
src/nimony/nimony_model.nim
src/nimony/sem.nim
tests/nimony/sysbasics/tdefault.nif
tests/nimony/sysbasics/tindex.nim

implement array/cstring indexing

---

tests/nimony/sysbasics/tnil.nim

This much seems to work, if I am missing any other uses of `nil` we can test/implement/fix them.

add test for nil pointers

---

src/gear3/expander.nim
src/nimony/sem.nim
tests/nimony/sysbasics/thooks.nif

follow up https://github.com/nim-lang/nimony/pull/316

clean up semhook

---

src/lib/nifbuilder.nim
tests/nimony/basics/t2.nif
tests/nimony/basics/tbinarytree.nif
tests/nimony/basics/tbool.nif
tests/nimony/basics/tcstring.nif
tests/nimony/basics/tdefinedarg.nif
tests/nimony/basics/tdistinct.nif
tests/nimony/basics/tenumsizes.nif
tests/nimony/basics/tfib2.nif
tests/nimony/basics/tforloop.nif
tests/nimony/basics/tgeneric_obj.nif
tests/nimony/basics/timportfromexcept.nif
tests/nimony/basics/tsetter.nif
tests/nimony/basics/ttemplate.nif
tests/nimony/basics/tvarargs.nif
tests/nimony/basics/twhen.nif
tests/nimony/sysbasics/tdefault.nif
tests/nimony/sysbasics/tdollar.nif
tests/nimony/sysbasics/thooks.nif

nifbuilder: don't add a space for unchanged lineinfo

---

src/gear3/lowerer.nim
tests/nimony/sysbasics/tforloops1.nim
tests/nimony/sysbasics/tforloops1.output

Todo: implements `instId` later

fixes simple nested for loop

---

src/gear3/basics.nim
src/gear3/expander.nim
src/gear3/lowerer.nim
tests/nimony/sysbasics/tbasics.nif
tests/nimony/sysbasics/tbasics.nim

so that `getType` could work on local variables

gear3: register local variables

---

src/hexer/expander.nim
tests/nimony/sysbasics/tdistincts.nim

This PR makes distinct types work

hexer: replace distinctT with internal types by skipping aliases 

---

src/nimony/deps.nim

Semcheck all files first and calculate deps. So that the later compilation could utilize the `idx` files

split makefile into two phase compilation

---

src/config.nims

refs https://github.com/nim-lang/Nim/pull/24620
Merging if it passes since this affects PRs

enable strictdefs, fixes CI

---

src/nifc/amd64/genasm.nim

I tested it only on Linux, not on Windows.

Make test code in nifc/amd64/genasm.nim runnable

---

src/hexer/duplifier.nim
src/hexer/lifter.nim
src/hexer/pipeline.nim
src/nimony/nimony_model.nim
src/nimony/programs.nim
src/nimony/typenav.nim

Integrate duplifier.nim into hexer

---

src/hexer/destroyer.nim
src/hexer/pipeline.nim

Integrate destroyer.nim into hexer

---

src/nimony/sem.nim

Split from #415, the set magics have generic return types so this was needed

instantiate return type of generic magics

---

src/nimony/sem.nim
tests/nimony/sysbasics/tconstarrlen.nif
tests/nimony/sysbasics/tconstarrlen.nim

closes #434
Might not be good enough long term

process const declarations in signature phase

---

src/hexer/nifcgen.nim
tests/nimony/sysbasics/tshr.nim
tests/nimony/sysbasics/tshr.output

fixes #426
`"($4)((NI$3)($1) >> (NU$3)($2))", # AshrI`
ref https://github.com/nim-lang/Nim/pull/8547
ref https://github.com/nim-lang/Nim/pull/11322

implements `shr` and `ashr`

---

src/nimony/sem.nim

Seems like they work fine after this so #433 could be closed

fix typo in sem for hook calls

---

src/hexer/nifcgen.nim

use bits from operand type for ashr

---

src/hexer/destroyer.nim
src/hexer/mover.nim
src/lib/lineinfos.nim
src/lib/nifcursors.nim
src/lib/nifstreams.nim
src/nimony/controlflow.nim
src/nimony/nimony_model.nim

WIP: move analyser

---

src/hexer/basics.nim
src/hexer/constparams.nim
src/hexer/hexer.nim
src/hexer/nifcgen.nim
src/hexer/pipeline.nim
src/nimony/deps.nim
src/nimony/sizeof.nim
tests/nimony/sysbasics/tbasics.nif
tests/nimony/sysbasics/tbasics.nim

integrate injectConstParamDerefs into hexer's pipeline

---

src/hexer/hexer.nim

fix hexer default bits

---

src/hexer/constparams.nim
src/hexer/pipeline.nim
src/nimony/typenav.nim
tests/nimony/sysbasics/tconstparams.nim

run xelim again after constparams if needed

---

src/hexer/nifcgen.nim
src/nifc/codegen.nim

This PR fixes https://github.com/nim-lang/nimony/issues/532 and https://github.com/nim-lang/nimony/issues/525

Fix #532: Using imported variables compiles without errors

---

lib/std/system.nim
lib/std/system/iterators.nim

Add `..<` iterator

---

src/nimony/sigmatch.nim

handle sink in sigmatch

---

lib/std/system/stringimpl.nim

`lib/std/strutils.nim` uses `newString` and `lib/std/parseopt.nim` import it.

Add newString proc

---

src/nimony/sem.nim
tests/nimony/errmsgs/tobjconstr.msgs
tests/nimony/errmsgs/tobjconstr.nim

fix and test object constructor errors

---

src/nifc/genexprs.nim
src/nifc/typenav.nim

Fix `getType` to returns the importc type symbol.

fixes #610

---

lib/std/system.nim
tests/nimony/sysbasics/tbasics.nif
tests/nimony/sysbasics/tconstarrlen.nif
tests/nimony/sysbasics/tforloops1.nif
tests/nimony/sysbasics/tintlitmatch.nif
tests/nimony/sysbasics/tstrings.nim

remove string magics from system

---

src/hexer/destroyer.nim
src/hexer/duplifier.nim
src/hexer/inliner.nim
src/nimony/nimony_model.nim
src/nimony/sizeof.nim
src/nimony/typeprops.nim

- renamed hasBuiltinPragma to hasPragma

refactorings

---

lib/std/hashes.nim

Workaround https://github.com/nim-lang/nimony/issues/675

Fix compile errors in lib/std/hashes.nim

---

lib/std/system/memory.nim
src/hexer/desugar.nim
tests/nimony/sysbasics/tbigsets.nim
tests/nimony/sysbasics/tsets.nif
tests/nimony/sysbasics/tsets.nim

refs #664
`card` still not implemented as it depends on the specific popcount implementation, the one in `countbits_impl` in original Nim heavily depends on defines

implement most set operations for array sets, runtime set constructors

---

src/hexer/nifcgen.nim
src/nimony/sem.nim
src/nimony/typenav.nim
tests/nimony/sysbasics/tbasics.nif
tests/nimony/sysbasics/tbasics.nim

make tuples compile

---

src/nimony/sem.nim
tests/nimony/generics/tgenerictuple.nim

fix generic tuple index

---

src/nimony/sem.nim
tests/nimony/generics/ttypevarconstr.msgs
tests/nimony/generics/ttypevarconstr.nim

disallow typevar object constructors

---

.gitignore
src/nimony/nifconfig.nim
src/nimony/nimony.nim
src/nimony/nimsem.nim
src/nimony/semos.nim

a quick follow up of #643 to allow nimony compile outside compiler folder

nimony: fix missing tools resolve when compiling outside compiler folder

---

src/hexer/iterinliner.nim
tests/nimony/sysbasics/twhileinfor.nim

fix while condition in for loop body

---

tests/nimony/ffi/deps/minlineimportc.nim
tests/nimony/ffi/inlineimportc.h
tests/nimony/ffi/tinlineimportc.nim

Add tests for issue https://github.com/nim-lang/nimony/issues/556

Add tests for issue #556

---

src/lib/nifindexes.nim
src/nimony/programs.nim
tests/nimony/sysbasics/topenarray.nim

fixes #728
Thought there might be issues with `var openarray` but it seems to work

fix index for multiple converters to the same type

---

src/nimony/sem.nim
tests/nimony/errmsgs/tifconderr.msgs
tests/nimony/errmsgs/tifconderr.nim

fix `if` condition error handling

---

src/hexer/nifcgen.nim
src/nimony/sem.nim
src/nimony/sembasics.nim
src/nimony/sigmatch.nim

mark remaining unused procs as `used`

---

doc/tags.md
src/hexer/desugar.nim
src/hexer/mover.nim
src/hexer/nifcgen.nim
src/hexer/xelim.nim
src/models/nifler_tags.nim
src/models/nimony_tags.nim
src/models/tags.nim
src/nifler/bridge.nim
src/nimony/controlflow.nim
src/nimony/deps.nim
src/nimony/nimony_model.nim
src/nimony/sem.nim

Split from #758 in case it's necessary

rename (from) to (fromimport)

---

tests/nimony/sysbasics/tseqarrayobj.nim

Follow up to https://github.com/nim-lang/nimony/pull/717
ref https://github.com/nim-lang/nimony/issues/691

adds test for types combines seq, array and object

---

lib/std/system.nim
lib/std/system/seqimpl.nim
tests/nimony/sysbasics/tbasics.nif
tests/nimony/sysbasics/tconstarrlen.nif
tests/nimony/sysbasics/temptyseq.nif

For visibility and in case we need it further up in the future

move HasDefault position in system

---

src/nimony/deps.nim

Simpler version of https://github.com/nim-lang/nimony/pull/799

Recompile when the passC/passL command line option was changed

---

src/nimony/sem.nim
tests/nimony/nosystem/deps/mwhen.nim
tests/nimony/nosystem/tcstring.nif
tests/nimony/nosystem/twhen.nif
tests/nimony/nosystem/twhen.nim
tests/nimony/stdlib/ttables.nim

enable evaluation for `const`

---

src/hexer/desugar.nim
src/nimony/typenav.nim
tests/nimony/sysbasics/tsets.nif
tests/nimony/sysbasics/tsets.nim

follows https://github.com/nim-lang/nimony/pull/681

fixes set `incl`, `excl`

---

src/nimony/asthelpers.nim
src/nimony/sem.nim
src/nimony/sembasics.nim
src/nimony/semimport.nim
src/nimony/semos.nim
src/nimony/semuntyped.nim

And `unquote` to `takeUnquoted`

rename `getIdent` to `takeIdent`

---

lib/std/system.nim
lib/std/system/countbits_impl.nim
lib/std/system/setops.nim
src/hexer/desugar.nim
tests/nimony/sysbasics/tsets.nif
tests/nimony/sysbasics/tsets.nim

implement `card`

---

src/hexer/iterinliner.nim
tests/nimony/sysbasics/twhileinfor.nim

todo: refactor related functions

hexer: transform while loop (eliminates `continue`)

---

src/hexer/constparams.nim
src/hexer/duplifier.nim
src/hexer/nifcgen.nim
src/nimony/programs.nim
tests/nimony/sysbasics/tlocaldecls.nim

follow up https://github.com/nim-lang/nimony/pull/812
Lifts local type decls into the top level

hexer: fixes local type decls

---

lib/std/system.nim
lib/std/system/iterators.nim
tests/nimony/concepts/tconceptiterator.nim
tests/nimony/sysbasics/tdefault.nim
tests/nimony/sysbasics/tforloops1.nif

adds default for arrays

---

src/hastur.nim

ref https://github.com/nim-lang/nimony/pull/713#issuecomment-2705026848

hastur: skip first three lines of valgrind output

---

tests/nimony/converter/deps/mgenericconverter.nim
tests/nimony/converter/timportedgenericconverter.nim

test generic converters across modules

---

lib/std/system/seqimpl.nim
tests/nimony/sysbasics/temptyseq.nif
tests/nimony/sysbasics/tvartuple.exitcode

Implements a part of https://github.com/nim-lang/nimony/issues/903

adds overflow checks to seq

---

src/nimony/sem.nim
src/nimony/sembasics.nim
src/nimony/semdata.nim
src/nimony/semos.nim
tests/nimony/modules/tqualifiedselfmodule.nim

Defines a symbol representing the current module and considers it in qualified symbols

implement self module sym

---

lib/std/system/stringimpl.nim

Implements https://github.com/nim-lang/nimony/issues/903 for strings
I think overflow checks are required only when adding two strings.
And if system memory size is smaller than or equals to 2^62 bytes, you will get out of memory error before getting overflow.
In `max(newLen, len + (len shr 1))`, if `len + (len shr 1)` overflowed, its value is smaller than `len` and `newLen`.
So `max(newLen, len + (len shr 1)) == newLen`.
When adding single character to a string, `len+1` overflows only if `len == high(int)`. But if `len == high(int)`, it fails to allocate memory.

adds overflow checks to strings

---

src/hexer/hexer_context.nim
src/nimony/typenav.nim
tests/nimony/valgrind/tnewref.nim

special case transformed ref deref dot in getType

---

lib/std/system.nim
lib/std/system/openarrays.nim
lib/std/system/seqimpl.nim
lib/std/system/stringimpl.nim
tests/nimony/iter/tforloops1.nif
tests/nimony/sysbasics/temptyseq.nif
tests/nimony/sysbasics/tvartuple.exitcode

- add a `rawData` proc in `seq[T]` like the one `string` has
- move `include memory` from stringimpl.nim  to system.nim
- move seq `toOpenArray` converter to openarrays.nim

seq: add `rawData` proc + some refactoring

---

src/hexer/duplifier.nim

fixes #920
In the case of `let x = toCStringTuple(my).raw`, `toCStringTuple(my).raw` is a location and needs to check its root doesn't own

fixes #920; destroyer is not emitted

---

lib/std/syncio.nim
lib/std/system/stringimpl.nim
tests/nimony/iter/tforloops1.nif
tests/nimony/sysbasics/tbasics.nif
tests/nimony/sysbasics/tsets.nif
tests/nimony/sysbasics/tstrings.nim
tests/nimony/sysbasics/tstrings.output

- add more terminating zero utils
- add the missing `fromCString` mentioned
- fix a possible redundant string copy in syncio `open`
- add cstring tests

string: add more cstring conversion utils

---

lib/std/setutils.nim
lib/std/system/setops.nim
tests/nimony/iter/tforloops1.nif
tests/nimony/stdlib/tsetutils.nim

- introduce `std/setutils` like nim 2.x
- add an items iterator to `set[T]` in `system/setops`
- add tests of `std/setutils` and `set[T]` items iterator

std: introduce setutils + add an items iterator to set[T]

---

lib/std/system.nim
lib/std/system/ctypes.nim
lib/std/system/memory.nim
lib/std/system/mimalloc.nim
src/hexer/nifcgen.nim
src/nimony/sem.nim
tests/nimony/sysbasics/temptyseq.nif

ref https://github.com/nim-lang/nimony/pull/933#issuecomment-2783983937

add ctypes

---

lib/std/system/stringimpl.nim
tests/nimony/sysbasics/tstrings.nim

adds newStringOfCap proc

---

.github/workflows/ci.yml

use chocolatey instead of winget for make

---

src/nimony/sigmatch.nim
tests/nimony/overload/tinvariantmatch.nim

fix linearMatch for importc int types

---

src/nimony/expreval.nim
src/nimony/semborrow.nim
src/nimony/sigmatch.nim
src/nimony/typeprops.nim
tests/nimony/const/tdistinctconv.nim

skip distinct for const conversions

---

src/nimony/sem.nim
src/nimony/semborrow.nim
tests/nimony/nosystem/tdistinct.nif
tests/nimony/sysbasics/tdistincts.nim

fixes #983; properly semcheck borrowed procs

---

src/hexer/xelim.nim
src/nimony/sem.nim
tests/nimony/errmsgs/tblocklineinfo.msgs
tests/nimony/sysbasics/tblocks.nim

Given a block, semcheck now tries to resolve expressions first

nimony: supports block expressions

---

src/hexer/nifcgen.nim
tests/nimony/sysbasics/mdistincts.nim
tests/nimony/sysbasics/tdistincts.nim

Calling inline proc calls proc with borrow pragma generates invalid C  code

---

src/nimony/sem.nim
tests/nimony/object/tcaseobject.nif

ref https://github.com/nim-lang/nimony/issues/1029
selects branches based on fields matching `setFields`
todo:

implements defaults for case object (selects branches): basic support

---

lib/std/system/panics.nim
src/hexer/vtables_backend.nim
tests/nimony/methods/tmof.nim
tests/nimony/methods/tmof.output

implement nil checks for methods/`of`

---

src/nifc/genstmts.nim
tests/nimony/sysbasics/tnil.nim

fixes #1046; nifc fixes local decl

---

src/nimony/sem.nim

ref https://github.com/nim-lang/Nim/pull/24938

nimony: selector of object variants must be of an ordinal type

---

src/nimony/derefs.nim
tests/nimony/errmsgs/ttupleviews.msgs
tests/nimony/errmsgs/ttupleviews.nim

todo: fixes it for Nim, which produces codegen errors

nimony: checking var types in the tuple returns

---

src/lib/nifindexes.nim
tests/nimony/errmsgs/tdistinctinfos.msgs
tests/nimony/errmsgs/tdistinctinfos.nim
tests/nimony/iter/tforloops1.nif
tests/nimony/sysbasics/temptyseq.nif
tests/nimony/sysbasics/tintlitmatch.nif

fixes #977
supersedes https://github.com/nim-lang/nimony/pull/1094

fixes #977; DistinctType(0) != 0 causes error message with wrong lineinfo

---

src/nimony/renderer.nim
tests/nimony/plugins/deps/mrender.nim
tests/nimony/plugins/deps/nim.cfg
tests/nimony/plugins/tcaseobjects.nim
tests/nimony/plugins/tcaseobjects.output
tests/nimony/plugins/trenderer.nim
tests/nimony/plugins/trenderer.output

plugins seem pretty neat to test compiler internals

My first plugin: basic tests for `asNimCode` + implements `asNimCiode` for case objects

---

src/nimony/expreval.nim
tests/nimony/const/tconstset.nim

This is required to compile `src/lib/nifreader.nim` with Nimony.

allows ranges of elements in const set

---

tests/nimony/arc/tensuremove.nim

ref https://github.com/nim-lang/nimony/issues/1192

adds tests for `ensureMove`

---

src/nimony/renderer.nim
tests/nimony/plugins/trenderer.nim
tests/nimony/plugins/trenderer.output

The test is not irrelevant. It fixes some code with `quoted`, which is reported during sem phases

fixes `asNimCode` for `QuotedX`

---

src/nimony/sem.nim
tests/nimony/errmsgs/temptycurly.msgs
tests/nimony/errmsgs/temptycurly.nim

follows up https://github.com/nim-lang/nimony/pull/1212

fixes empty set/array with wrong expected types

---

src/nifler/bridge.nim

allows lambda to have empty nodes

---

src/hexer/vtables_backend.nim

the code:
`a.nim`
```nim
type
Compositor* = object of RootObj
```
`b.nim`
```nim
import a
let c = Compositor()
```
was crushing the compiler
```
/d/code/langs/nimony/src/hexer/hexer.nim(99) hexer
/d/code/langs/nimony/src/hexer/hexer.nim(96) handleCmdLine
/d/code/langs/nimony/src/hexer/nifcgen.nim(1919) expand
/d/code/langs/nimony/src/hexer/pipeline.nim(90) transform
/d/code/langs/nimony/src/hexer/vtables_backend.nim(832) transformVTables
/d/code/langs/nimony/src/hexer/vtables_backend.nim(597) tr
/d/code/langs/nimony/src/hexer/vtables_backend.nim(561) trLocal
/d/code/langs/nimony/src/hexer/vtables_backend.nim(587) tr
/d/code/langs/nimony/src/hexer/vtables_backend.nim(287) trObjConstr
/d/code/langs/nimony/src/hexer/vtables_backend.nim(247) maybeImport …
```

fixes vtable import when no derived type declared

---

src/hexer/destroyer.nim
src/hexer/duplifier.nim
src/nimony/decls.nim
tests/nimony/arc/texplicit_hooks.nim

fixes #1168; generates `haddr` for `var T` destroy hooks

---

doc/nifc-spec.md

follow up to https://github.com/nim-lang/nimony/pull/1252

adds anonymous object and union to NIFC spec

---

src/nimony/semdecls.nim
tests/nimony/sysbasics/tbasics2.nim

fixes #1231; Unable to pass anonymous procedure to function

---

src/nimony/semdecls.nim
tests/nimony/sysbasics/tbasics2.nim

Uses `ExprX` to keeps the transformation in place

improves anonymous procs for closures

---

src/nimony/semcall.nim
src/nimony/sigmatch.nim
tests/nimony/sysbasics/tbasics2.nim

implements https://github.com/nim-lang/nimony/issues/1269
prefers iterators in a for loop context; otherwise prefers procs as done in Nim

closes #1269; prefers iterators in a for loop context

---

src/nimony/sem.nim
tests/nimony/object/tcase1.msgs
tests/nimony/object/tcase1.nim
tests/nimony/object/tcase2.msgs
tests/nimony/object/tcase2.nim

ref  https://github.com/nim-lang/nimony/issues/992

improves case object error messages

---

src/nimony/enumtostr.nim
src/nimony/semdecls.nim
src/nimony/semtypes.nim
src/nimony/typeprops.nim
tests/nimony/enums/tenumnameconflict.msgs
tests/nimony/enums/tenumnameconflict.nim
tests/nimony/enums/tenumnames.nim
tests/nimony/enums/tenumnames.output

Allows enum names to be overloaded

---

src/nimony/semcall.nim
tests/nimony/iter/tforloops.nif
tests/nimony/iter/tforloops1.nif
tests/nimony/nosystem/t2.nif
tests/nimony/nosystem/tforloop.nif
tests/nimony/nosystem/tgeneric_obj.nif
tests/nimony/nosystem/ttemplate.nif
tests/nimony/sysbasics/tbasics2.nim
tests/nimony/sysbasics/tderefs2.nif
tests/nimony/sysbasics/temptyseq.nif

fixes #1307; properly semcheck return types

---

doc/tags.md
src/hexer/nifcgen.nim
src/models/nimony_tags.nim
src/models/tags.nim
src/nimony/deps.nim
src/nimony/sem.nim
src/nimony/semdata.nim

math module needs `{.passL: "-lm".}` to use C math functions.

implements passL pragma

---

lib/std/system/arithmetics.nim
tests/nimony/generics/tnoconstraintbad.msgs
tests/nimony/generics/tnoconstraintbad.nim

They are frequently used in math module.

adds `+=`, `-=` and `*=` for ints and floats

---

lib/std/system.nim
lib/std/system/dyncalls.nim
lib/std/system/panics.nim
src/nimony/expreval.nim
src/nimony/semdecls.nim
tests/nimony/errmsgs/tdistinctinfos.msgs

required by https://github.com/nim-lang/nimony/issues/1337 by `std/encodings`

port dyncalls to system

---

src/nimony/derefs.nim
tests/nimony/errmsgs/topenarray_errors.msgs
tests/nimony/errmsgs/topenarray_errors.nim

Fixes `firstArgIsMutable` proc to check first argument.

fixes #1334

---

src/nifc/codegen.nim
src/nifc/genstmts.nim
tests/nimony/sysbasics/deps/mconsts.nim
tests/nimony/sysbasics/tconsts.nim

fixes #1345; make local consts `static` in nifc to avoid conflicts

---

tests/nimony/errmsgs/topenarray_errors.msgs

https://github.com/nim-lang/nimony/pull/1350 changed the location generates error in the test code.
So this file need to be updated to pass the test.

fixes .msgs file to pass tests

---

src/nimony/semdecls.nim
tests/nimony/errmsgs/twrongpragmas.msgs
tests/nimony/pragmas/tmacro_invocations.nim
tests/nimony/pragmas/tmacro_invocations.output

ref https://github.com/nim-lang/nimony/issues/524

implements rewrite rule: proc pragmas can also be macro invocations

---

lib/std/math.nim

math module still uses `signbit`, `fpclassify` and `isnan` macros because C stdlib doesn't provide them as functions.

removes C type-generic macros from math module

---

lib/std/private/syslocks.nim
tests/nimony/sysbasics/tlocks.nim

ref  https://github.com/nim-lang/nimony/issues/1360
also a test for dynlib pragmas for windows

fixes `std/locks` on windows

---

lib/std/parseutils.nim
lib/std/strutils.nim
tests/nimony/stdlib/tparseutils.nim
tests/nimony/stdlib/tstrutils.nim

added `parseHex` in `lib/std/parseutils.nim` as `unescape` func uses it.

ports strutils.nim in Nim 2 to Nimony part2

---

src/nimony/semtypes.nim
tests/nimony/sysbasics/tbasics2.nim

fixes #1377
unblocks https://github.com/nim-lang/nimony/pull/1374

fixes #1377; fully evaluates arrays Slice index

---

lib/std/intsets.nim
lib/std/tables.nim
tests/nimony/stdlib/ttables.nim

follows up https://github.com/nim-lang/nimony/pull/1405

adds `raises` for `[]` + `getOrQuit` for stdlibs

---

lib/std/cmdline.nim
lib/std/windows/winlean.nim
tests/nimony/stdlib/tcmdline.nim

porting `std/cmdline` to Nimony

---

doc/tags.md
lib/std/system.nim
src/models/nifler_tags.nim
src/models/nimony_tags.nim
src/nimony/sem.nim
tests/nimony/nosystem/deps/modb.nim
tests/nimony/nosystem/t1.nim
tests/nimony/nosystem/t2.nif
tests/nimony/nosystem/t2.nim
tests/nimony/nosystem/tdistinct.nif
tests/nimony/nosystem/tdistinct.nim
tests/nimony/nosystem/tgeneric_obj.nif
tests/nimony/nosystem/tgeneric_obj.nim
tests/nimony/nosystem/ttemplate.nif
tests/nimony/nosystem/ttemplate.nim
tests/nimony/nosystem/tvarargs.nif
tests/nimony/nosystem/tvarargs.nim
tests/nimony/sysbasics/ttypeof.nim

follow-up to https://github.com/nim-lang/nimony/pull/1431.

adds mode parameter to typeof
