src/lib/nifreader.nim
src/nifc/genexprs.nim

> Unsigned numbers always have a `u` suffix.
Otherwise the trailing `u` is parsed as an ident.

fixes suffix for numbers

---

src/nifc/genexprs.nim
tests/nifc/issues.nif

(add i8 4 5)
before
```nim
(NI8)4 + 5
```
After
```nim
(NI8)(4 + 5)
```

fixes typedBinOp gen

---

src/config.nims
src/gear2/bridge.nim
src/gear2/gear2.nim
src/lib/keymatcher.nim
src/lib/nifbuilder.nim
src/lib/nifcursors.nim
src/lib/nifindexes.nim
src/lib/nifreader.nim
src/lib/packedtrees.nim
src/nifc/amd64/emitter.nim
src/nifc/amd64/machine.nim
src/nifc/makefile.nim
src/nifc/nifc.nim
src/nifc/nifc_model.nim
src/nifc/typenav.nim
src/nifgram/nifgram.nim
src/nifler/bridge.nim
src/nifler/emitter.nim
src/nifler/nifler.nim
src/xelim/xelim.nim
src/xelim/xelim_model.nim
src/xelim/xelim_transformer.nim
src/xelim/xelim_typenav.nim

Compiler codebase has `nimPreviewSlimSystem` on, do the same here and without conditions since it's unlikely we will have to compile nif with a < 2.0 compiler. It's easy to make conditional if we do though.
Workarounds for the csources_v2 (2.0) compiler are also added for bootstrapping Nim. These are for the lack of non-var destructors and a template resolution bug with dot fields in `packedtrees`. `ensureMove` also does not exist on 2.0 but this can also be fixed by making `ensureMove` a no-op on older versions in the Nim repo standard library for just bootstrapping.
Tested at https://github.com/nim-lang/Nim/pull/24262.

use nimPreviewSlimSystem everywhere, workarounds for 2.0 compiler

---

src/nifc/cprelude.nim
tests/nifc/issues.nif

`IL64` is generated in the codegen [here](https://github.com/nim-lang/nif/blob/a32cd8877c99c0cfdde87c3544b4d5ef676e7b5e/src/nifc/codegen.nim#L150-L155) but was not defined in the C prelude, now it is.
Also tests the generation and parsing of edge integer values like `-9223372036854775808`.

define required IL64 macro for large negative int64

---

src/nifc/bat.nim
src/nifc/makefile.nim
src/nifc/mangler.nim
src/nifc/nifc.nim
src/nifc/selectany.nim
tests/nifc/app.c.nif
tests/tester.nim

e.g. without mangling, `test.c.nif` will generate a binary called `test.c` which is quite confusing

remove affixes in the filenames from the binary name

---

doc/nifc-spec.md
src/nifc/amd64/genasm_e.nim
src/nifc/amd64/genasm_s.nim
src/nifc/amd64/register_allocator.nim
src/nifc/cprelude.nim
src/nifc/genexprs.nim
src/nifc/native/analyser.nim
src/nifc/nifc_grammar.nif
src/nifc/nifc_model.nim
src/nifc/preasm/genpreasm_e.nim
src/nifc/typenav.nim
tests/data/nifc_grammar.nim
tests/nifc/issues.nif

Unlike `sizeof`, `alignof` and `offsetof` only expect a type in C, so `sizeof` also now accepts only types instead of only expressions.

nifc: add alignof & offsetof, make sizeof only take type

---

src/nifler/bridge.nim

from `(let mx . . 4 +123)` to `(let m x . . 4 +123)`

fixes nifler generates incorrect visibility field

---

src/nifc/codegen.nim
src/nifc/cprelude.nim
src/nifc/genexprs.nim
src/nifc/nifc.nim
tests/nifc/issues.nif
tests/nifc/try.nif

It generates `NIM_THREADVAR NB8 NIFC_ERR_;` for the main module.
When it is used in the other module, `extern NIM_THREADVAR NB8 NIFC_ERR_;` will be produced.

implements `(err)` as a threadlocal variable

---

src/nimony/sem.nim

Calling sigmatch causes an assert failure rather than propagating the `undeclared identifier` error.

nimony: don't call sigmatch on undeclared identifier

---

src/gear3/expander.nim
src/lib/nifcursors.nim
src/nimony/nimony_model.nim
src/nimony/sem.nim
src/nimony/tests/tbasic.nim

Mirrors [Nim's implementation](https://github.com/nim-lang/Nim/blob/e7f48cdd5c17cbd0c1c74c2c1f360ae2ea122b64/compiler/semstmts.nim#L140).
`endRead` and `skipParRi` had some extra parameters that were not needed. Single word pragmas also had a bug where they added a `ParLe` token but not a `ParRi` one.

nimony: support discardable

---

src/lib/nifcursors.nim

It seems `Cursor.rem` should have a number of `PackedToken`, not a number of bytes.

Fix nifcursors.setSpan

---

src/nifc/mangler.nim
tests/nifc/issues.nif

This is for things like `unsigned char` to be represented more easily.

nifc: add test for escaped .c identifiers

---

src/nimony/sem.nim

refs #136, refs #133
Since #133 `tests/basics/t1` gives:
```
src/nimony/tests/basics/t1.nim(38, 12) Error: type mismatch: got: . but wanted: (i -1)
```
but the tester does not seem to catch this, maybe it doesn't produce a failure exit code?
The issue itself is fixed by just not modifying `it.typ` at all since it's not used after.

nimony: fix discardable after combineType changes

---

src/nifc/gentypes.nim
tests/nifc/issues.nif

Before, types with fields with `.c` types would give undeclared identifier errors in this code, but it's not necessary to track these since they're imported from C.

nifc: ignore undeclared .c types in type dependencies

---

src/nimony/sem.nim
src/nimony/tests/basics/t1.nim

nifler produces unhandled pragmas leaving identifier raw
```
(pragmas inline exportc)
```
and so on

Nimony: fixes semPragma

---

src/gear3/expander.nim
src/nifc/amd64/emitter.nim
src/nifc/amd64/genasm.nim
src/nifc/codegen.nim
src/nifc/preasm/genpreasm.nim
src/nifgram/nifgram.nim
src/nimony/programs.nim

so that it works better with `strictdefs`

mark `error` functions `{.noreturn.}`

---

src/nifler/bridge.nim
src/nimony/sem.nim
src/nimony/tests/basics/t1.nim

`relLineInfo(it, n, c)` should be added before a node, not after a node. It causes conflicts with the lineinfos of the internal nodes otherwise and produces an UnknownToken with consecutive lineinfos.
e.g.
```
(enum 14,1
(efld 14,1 ~8 false . . . +0)
```

nimony: fixes enum types

---

src/nimony/nimony.nim

It's annoying for debugging `nimony` when I change the code `nifler`. I expect to force a rebuild of `nifler` and force `nifler` to generate something different instead of relying on cache mechanism to do nothing.

nimony: force a rebuild for `nifler` to rebuild the phase one

---

src/nifc/nifc_model.nim
tests/nifc/issues.nif

Calling `addSymbol` escapes the output, giving something like `NIM_ALIGN(\2B16)`.

nifc: fix toString for numbers, fixes align pragma

---

src/nifc/codegen.nim
src/nifc/gentypes.nim
tests/nifc/issues.nif

This is what Nim uses, it might cause issues when adding attributes (currently it does `typedef void (*__attribute(foo)__ bar)` unilke no call convention which does `typedef void (__attribute__(foo) *bar)`) but this can be addressed when attributes are used for proc types, I can't find an example of either version working.

nifc: use _PTR macros for proc type call conventions

---

src/nimony/sem.nim

Fixes `bitnot` and includes `neg`

nimony: split typed arith ops into binary and unary

---

src/gear3/expander.nim
tests/gear3/gear3_helloworld.nif

implements `enumT`: adds an extra parameter `dest: var TokenBuf` for `traverseExpr`, `loop`, `traverseType` etc. Because we need to evaluate fields in advance for later use to get the enum types, the result of fields need to be stored in a temp `TokenBuf`.

gear3: implements enumT

---

src/nimony/builtintypes.nim
src/nimony/sem.nim
src/nimony/tests/basics/t1.nim

Typedesc tuples aren't implemented (i.e. `(int, string)`), they could be but it would hinge on type expressions being accepted as regular expressions, which is not the case currently but probably should be eventually. Then we would check for `TypedescT`.

nimony: tuple constructors

---

src/nimony/sem.nim
src/nimony/sigmatch.nim

The only remaining use of `combineType` is `producesVoid`/`producesNoReturn`, which just check that `void` or `auto` were expected (and noreturn assimilates into the expected type otherwise).

nimony: fix wrong uses of commonType, use for syms, dot, `suf`

---

src/nimony/sigmatch.nim

`asTypeAlias` only allows type symbols with the implementation either being other type symbols or a generic invocation, this needed tuple types to be special cased in #179. However this will need other types to be whitelisted as well, so the restriction is removed. Maybe there is still a reason why these were whitelisted though?

nimony: allow any type aliases in sigmatch

---

src/nimony/sigmatch.nim

The old `singleArg` had a side effect of code generation so it should only be called once

nimony: fixes duplication code generation for type alias

---

src/nimony/expreval.nim
src/nimony/sem.nim

This acts as a primitive version of the compile time VM so that we can handle the most common constant expressions in Nim code. I had thought `defined`/`declared` would also be evaluated here, but currently they are immediately resolved in semchecking, which could be sufficient overall including for things like `sizeof` (though not when they depend on an unresolved generic parameter i.e. `sizeof(T)`, but this would be resolved in semchecking during instantiation too).
Might be ugly and low on comments, couldn't think of how to clean it up. `semConstBoolExpr` is unused for now but will likely be used.

nimony: expression evaluator for simple constant expressions

---

src/nimony/sem.nim

refs #192
We would also need to reverse the order when traversing `array[3, int]`, but this isn't done yet

nimony: make array type order same as in gear3, nifc

---

src/nimony/sem.nim

As mentioned in #197. The cases I can think of where the received type can subsume the expected type would be generic typeclasses or `auto`, but these aren't encountered here since typevars aren't set (`auto` is handled as a special case first). And these would probably need a separate instantiation mechanism if they were encountered. So unless we can think of other cases where this happens, it's simpler to always use the expected type as a general rule.

nimony: make commonType always give expected type

---

src/nimony/sem.nim

As outlined [here](https://github.com/nim-lang/nif/pull/194/#issuecomment-2538356468), would also have a special case for generic routines but there is nothing to call for them yet. Anything that is not an invocation is treated as an overloaded call to `[]`, which needs to have magic overloads.
Note for the future: https://github.com/nim-lang/Nim/issues/9997, standalone instantiations of symchoices shouldn't generate a symchoice of the instantiated symbols as Nim currently does, instead it should probably be treated as an "instantiation choice" either remaining as a bracket over a symchoice or its own node kind that can later be type-fit to a specific instantiation

nimony: subscripts with invocations as special case

---

src/nimony/sem.nim

keeps it consistent with ObjectT: since nifc specifies `(dot Expr Symbol Number)` for field accesses

nimony: fixes dot access for tupleT

---

src/nimony/sem.nim
src/nimony/sembasics.nim
src/nimony/tests/basics/t1.nim
src/nimony/tests/basics/tgeneric_obj.nif
src/nimony/tests/basics/ttemplate.nif

Calls special case dot expression callees on a syntax level, if the dot expression ends up not being a builtin dot or being a builtin dot that doesn't have a proc type, the callee is rebuilt from the field identifier and the LHS of the dot is added as an argument. Standalone dot expressions that don't resolve to a builtin dot are also transformed into a call and semchecked as such.
This is achieved by moving the previous behavior of `semDot` into `tryBuiltinDot` which takes an already built LHS cursor and a field name identifier and builds a dot expression on `c.dest`, then returns the status of whether the dot expression was a builtin or not.

nimony: implement UFCS

---

src/nimony/sem.nim
src/nimony/sigmatch.nim
src/nimony/tests/basics/tgeneric_obj.nif
src/nimony/tests/basics/tgeneric_obj.nim

Magic types like `array`, `set` are constructed with the same syntax as regular generic invocations, so they need special handling in `semInvoke`. In the case of `array`, the order of the children differs between the invocation and the NIF tag, so the magic type is built after the arguments have been processed.
If necessary the output could also be saved into a symbol (`targetSym`) and put in the instantiation cache but this isn't done for now. Also, if any type arguments are generic then it stays as an `InvokeT` and isn't inlined into a magic, this could be changed as well since it's not the case for compound types that aren't invoked magics, i.e. proc types, tuples.
There was a bug in `linearMatch`, every use of it expects the starting ParLe to be encountered inside the `linearMatch` …

nimony: implement invocations of magic types (array, set etc)

---

src/nimony/sem.nim
src/nimony/sigmatch.nim
tests/nimony/basics/tfib2.nif
tests/nimony/basics/tfib2.nim

Constraints are now checked for the matched generic parameters but missing/extra arguments are still ignored. Standalone instantiations of generic procs are also still not implemented.
`genericArgs` is expected to be a cursor to a stream of types, so when `semLocalType` receives values with `AllowValues`, it should wrap them in a `static` type that also contains the type of the expression, so that it can be matched in sigmatch. This is also not done yet because the representation of arrays would need to change accordingly, currently it just stores an integer.

nimony: support explicit generic arguments in calls

---

src/nimony/sem.nim
tests/nimony/basics/tbool.nif
tests/nimony/basics/tbool.nim

fixes #223
Not very elegantly written but works well enough, a prettier version might have a `magic: TypeKind` field in `EnumTypeState` instead but this would require parsing the magic tag, then again this is the only occurence where an enum has a magic tag

special handling for `true`/`false` as fields of magic enum `bool`

---

src/gear3/expander.nim
src/nifc/genstmts.nim
tests/gear3/gear3_helloworld.nif

transforms
```
(case 5 global.0 ,1
(of 
(set 3 +11 7 +12 11 +13 15
(range +8 3 +9)) 2,1
(stmts 
(discard 8 +1))) ,3
```
into
```
(case 5 global.0 ,1
(of 3
(ranges +11 4 +12 8 +13 12
(range +8 3 +9) ~3) 2,1
(stmts 
(discard 8 +1))) ,3
```
TODO:

gear3: transform case `set` into `ranges`

---

src/nimony/sem.nim

Magic expressions produced by overload resolution may need to be semchecked. However this doesn't make sense for all magics, so a whitelist is used.
`semCmp` and `semTypedArithmetic` are not included in the semchecked magics but they are fixed so that semchecking those magics works regardless: The comparison magics are now typed so `semCmp` is updated accordingly, also it erroneously recursed over `it` rather than using a new item for the operands which expect a different type than the comparison expression itself (which expects `bool`). Typed arithmetic magics are also adapted to `commonType`.

semcheck some magics after overloading

---

src/hastur.nim
src/nimony/expreval.nim
src/nimony/magics.nim
src/nimony/nimony.nim
src/nimony/nimony_model.nim
src/nimony/sem.nim
src/nimony/semdata.nim
tests/nimony/basics/deps/mwhen.nim
tests/nimony/basics/twhen.nif
tests/nimony/basics/twhen.nim

Hastur also adds `--isMain` to the arguments for every test, maybe this could be restricted to files starting with `t`.
Also adds disabled behavior that makes `const` definitions evaluate their values.

implement `isMainModule` as magic, fix `not` and expreval

---

src/nimony/sem.nim
tests/nimony/basics/t2.nif
tests/nimony/basics/t2.nim

refs https://github.com/nim-lang/nimony/pull/250#discussion_r1894131519
Previously `resId` was never set and [this condition](https://github.com/nim-lang/nimony/blob/0d019e7d867265ad02f25b7748abae915f059ccc/src/nimony/sem.nim#L579) was always false.

fix expression return, set result symbol for current routine

---

src/gear3/expander.nim
src/nimony/expreval.nim
src/nimony/magics.nim
src/nimony/nimony_model.nim
src/nimony/sem.nim
src/nimony/sembasics.nim
src/nimony/sigmatch.nim
tests/nimony/basics/tdefinedarg.nif
tests/nimony/basics/tdefinedarg.nim
tests/nimony/basics/tundeclaredarg.msgs
tests/nimony/basics/tundeclaredarg.nim

closes #242
Similar to #221 except that `untyped` now acts the same as `typed` (which is now added), the original AST is at the start of the error tokens and not at the end, and only the errors described in #242 keep the original AST for now.
`defined` and for now `declared` manually strip all errors from the AST they receive and build strings from them, with `defined` now also supporting dotted identifiers. In the future `declared` could fully type its argument and check for specific errors instead of looking up an identifier based off of the raw AST.
`AllowUndeclared` is added that keeps identifier tokens as is instead of wrapping them in error tokens when they are undeclared. `semCall` uses this for the callee part so that we don't have to specifically strip undeclared identifier …

optional original AST after error tokens, make `defined` work with typed args

---

src/nimony/sem.nim
tests/nimony/basics/timportlist1.nim
tests/nimony/basics/timportlist2.nim
tests/nimony/basics/tincludelist.nim

The `import a, b, c` syntax was not implemented, although `import foo/[a, b, c]` was, both are tested

fix & test import/include lists

---

src/gear3/expander.nim
src/nimony/magics.nim
src/nimony/nimony_model.nim
src/nimony/sem.nim
src/nimony/sigmatch.nim
src/nimony/typeprops.nim
tests/nimony/basics/tgeneric_obj.nif
tests/nimony/basics/tgeneric_obj.nim
tests/nimony/basics/timportfromexcept.nif

Range types are added so that we can implement custom index types for arrays as well as the `array[0..2, ...]` syntax. Now, fully resolved array types always have a range type as their index type, but unresolved array types do not, as the unresolved index type can either resolve to a range type or might have to be converted to one. 
Outside of array indexes, range types themselves don't have much functionality, in sigmatch they match their base type but their base types don't match them yet. Float ranges also aren't implemented.
Range types have the representation `(rangetype Type IntLit IntLit)` where its children are the base type followed by the bounds which are always integer literals. They may need to allow unsigned integer literals in the future as well but for array indexes this …

add range types to use for array index types

---

src/gear3/expander.nim
src/nifgram/nifgram.nim
src/nimony/expreval.nim
src/nimony/sem.nim
tests/gear3/gear3_helloworld.nif
tests/nimony/basics/t1.nim
tests/nimony/basics/tbool.nif

```nim
type
Color = enum
Red = "r1", Green = "r12", Blue = "r3"
```
Transform into `(0, "r1")` pairs.
TODO：

nimony: fixes enum fields

---

src/nimony/sem.nim
tests/nimony/basics/tsetter.nif
tests/nimony/basics/tsetter.nim

closes #270
Field setters falling back to dotcalls is left unimplemented, if it's needed then we can disable field setters until it's implemented. Curly subscript assignments are also unimplemented but are much simpler since they always build `{}=`.

nimony: implement dot/subscript setters

---

src/nimony/sem.nim
src/nimony/semdata.nim
src/nimony/sigmatch.nim
tests/nimony/basics/tgeneric_obj.nif
tests/nimony/basics/tgeneric_obj.nim

1. Instantiated procs were only mapped to the types of their parameters, not which routine symbols they were instantiated from
2. Magic type invocations (i.e. `array[I, T]`) were left as `(at (array) I T)` in generics
3. `inc inGeneric` leaked in `semGenericParams` for type sections since they did not push a new routine
4. `linearMatch` matching a generic parameter only skipped a single token after doing so, i.e. `(array T I)` matching `(array (i -1) ...)` would match `T` to `(i -1)` then move to the next token after `(i`, matching `I` to `-1`
`inc inGeneric` leaking means procs were not instantiated in some of the tests, the `HSlice[T, U]` return type of `..` remains as `InvokeT` after instantiation rather becoming a symbol which causes issues, probably `semLocalType` isn't called on the …

fix issues with generic proc matching

---

src/nimony/sem.nim
tests/nimony/basics/tgeneric_obj.nif
tests/nimony/basics/tgeneric_obj.nim

Brings back disabled test from #274, cached invocation types outputted `(at BaseType ...) InstType` rather than just `InstType`
Every single call to `typeToCursor` uses a cursor that is supposed to contain a single type and nothing after, maybe we can enforce that `typeToCursor` consumes a single tree and nothing else is left in the buffer to catch these bugs.

fix cached invocation types

---

src/lib/nifprelude.nim
src/nifler/nifler.nim
tests/tester.nim

`{.push warning[UnusedImport].}` only suppresses the warning since recent PR https://github.com/nim-lang/Nim/pull/24554 but we test for devel anyway

fix unused import warnings

---

src/nimony/decls.nim
src/nimony/typeprops.nim

Enum types no longer have a base type part and enum fields have the same representation as any other local, which `asEnumField` does not match. Enum field values are also tuples now.

fix asEnumDecl, remove asEnumField, fix its uses

---

src/gear3/expander.nim

can be applied to consts in the future

gear3: eliminates discard without arg

---

src/gear3/expander.nim

Conversions to distinct types are not needed, vice versa

gear3: remove Dconv

---

src/nifler/bridge.nim
src/nimony/lib/std/system.nim
src/nimony/magics.nim
src/nimony/nimony_model.nim
src/nimony/sem.nim
src/nimony/sembasics.nim
tests/nimony/basics/t1.nim
tests/nimony/basics/tfib2.nif
tests/nimony/basics/tgeneric_obj.nif
tests/nimony/basics/ttemplate.nif
tests/nimony/sysbasics/tdefault.nif
tests/nimony/sysbasics/tdefault.nim

closes #276
Object constructors and the default object magic both build an object constructor containing every field in the object constructor: first starting with the fields of the most shallow base type of the object type (if it exists), then of its base type and so on, and finally adding the fields from the original object type. This order is the same one used in the VM in the old compiler, could be changed.
Object constructors build a table of the given field assignments first, then when the output object constructor is being built, the table is looked up for each field to see if it has been set and the assignment is used if it has. I'm not sure what the optimal way to do this is. Currently it looks up the object fields when initially going through the object constructor and maps the …

implement default, object & tuple as magics, full object constructors

---

src/gear3/expander.nim
src/nimony/lib/std/system.nim
src/nimony/magics.nim
src/nimony/nimony_model.nim
src/nimony/sem.nim
src/nimony/sigmatch.nim
tests/nimony/sysbasics/tdefault.nif

Currently entirely a magic unlike `default` for a couple reasons:
* The overload for either `int` and `uint` would be hard to represent at this point
* Enums and range types require the use of a magic
* The original overloads also use a magic

implement low/high as magic

---

src/gear3/expander.nim
src/nifc/gentypes.nim
src/nifler/bridge.nim
src/nimony/decls.nim
src/nimony/enumtostr.nim
src/nimony/sem.nim
tests/gear3/gear3_helloworld.nif
tests/nimony/basics/tbool.nif
tests/nimony/sysbasics/tdefault.nif
tests/nimony/sysbasics/tdollar.nif

refs #162 and #284
The issue before was that nifler didn't push an empty token for them
Guessing sem needs to set the base type, could do this now or in a followup PR

add back base types to enums

---

src/lib/nifbuilder.nim

According to the `nif` spec, there are 3 forms for line infos:
```
1. `<column-diff>`
2. `<column-diff, line-diff>`
3. `<column, line, filename>`
```
If the `line-diff` is 0 but `filename` is different, It should generate `1;;filename` or `;;filename` instead of `1;filename` which causes problems for parsing

nifbuilder: fixes LineInfo for filenames

---

lib/std/system.nim
src/nimony/magics.nim
src/nimony/sem.nim
tests/nimony/sysbasics/tdefault.nif
tests/nimony/sysbasics/tderef.nim

refs #304
Something to note is that the return type of the overload is `var T` but this could generate a hidden deref when matching to `T` or no hidden addr when matching to `var T` which would be wrong, so instead `semDeref` generates a type of `T`. Something may be wrong here

implement deref as overload of `[]` (and `[]=`)

---

src/nimony/sigmatch.nim
tests/nimony/generics/tdoubleptr.nim

1. Use the original `f` and `a` passed to `linearMatch` for error messages
2. `m.inferred[fs]` was passed to `linearMatch` as an argument but `linearMatch` mutates its arguments, use an intermediary variable
3. Progress typevar symbol tokens after matching them via `linearMatch`
4. Break the loop in `linearMatch` after matching any token if the nesting level is 0, needed when matching single tokens by themselves e.g. symbols

fix linearMatch for typevars

---

src/nimony/sem.nim
tests/nimony/basics/tbinarytree.nif
tests/nimony/basics/tbinarytree.nim

For types of the form `type Foo = object; ref Foo` rather than `type Foo = ref object` which doesn't work yet
They are treated the same as regular object types in these expressions in sem

allow object constructors and dot fields for structural ref objects

---

src/nimony/sem.nim

i.e. in `Foo[int]`, `Foo` should not be inlined
A followup might be to add inlining logic to `semInvoke` for non-nominal values, maybe even with unresolved parameters, i.e. with `type Foo[T] = ref Bar[T]`, `Foo[U]` in a generic context could inline to `ref Bar[U]`

keep generic type symbols as symbols in semTypeSym

---

src/gear3/expander.nim
src/nimony/sem.nim
tests/nimony/sysbasics/tdefault.nif
tests/nimony/sysbasics/tdefault.nim

Also made gear3 stop traversing generic bodies at all for now, the alternative is to do something like [this](https://github.com/nim-lang/nimony/pull/326/commits/03b1dc130a1004b6c8983baa702b84f7853d152e#diff-d86ef2b503c1ba11be6f2f477871862aea3ab8e5432038ed6923b9873fd6ce76) which is not comprehensive enough. Don't know if we'll need to traverse them eventually, can add a comment about it if so.

object constructors and dot fields for generic objects

---

src/gear3/expander.nim
src/nimony/nimony_model.nim
src/nimony/sem.nim
src/nimony/semdata.nim
tests/nimony/sysbasics/thooks.nif
tests/nimony/sysbasics/thooks.nim

fixes #272; nimony: implements type bound =hooks

---

src/nimony/sem.nim
tests/nimony/generics/tnestedobj.nim
tests/nimony/generics/trecursiveobj.nim

This allows things like nested generics to compile due to converting InvokeT types to sym types.
The symbol is saved to the type instantiation cache before semchecking so that recursive types do not try to infinitely create a new instantiation. However the type symbol cannot be loaded until the semchecking is done, so if anything tries to introspect the type in its own definition it will fail when trying to load it. For now this is not an issue. Maybe a solution is to perform a `SemcheckTopLevelSyms` phase on the substituted type first, though the AST of the symbol would then be substituted but not semchecked type AST.
A followup would be to inline the produced types if they are structural instead of giving their symbols. Edit: Actually this is just a `semTypeSym` call, and requires …

semcheck substitution output of invoked generic types

---

src/nimony/sem.nim
tests/nimony/basics/tfib2.nif
tests/nimony/sysbasics/tdefault.nif
tests/nimony/sysbasics/tdefault.nim

`requestRoutineInstance` only substitutes the return type and doesn't semcheck it, only giving the cursor of the return type from the delayed instantiated proc declaration. So we semcheck the given return type in `resolveOverloads`, though we could also do this inside `requestRoutineInstance` and put the semchecked type in the delayed proc too.

semcheck substituted return type of generic calls

---

src/nimony/sem.nim
tests/nimony/generics/tnestedobj.nim
tests/nimony/generics/trecursiveobj.nim

Followup to #332
This allows structural/alias type instantiations to be inlined. For recursive/forward types, an earlier pass in the `SemcheckTopLevelSyms` phase saves the substituted AST as the type symbol AST.

sem output type sym by semInvoke, use 2 phases

---

src/gear3/expander.nim
src/nimony/sem.nim
tests/nimony/sysbasics/tbasics.nif
tests/nimony/sysbasics/tbasics.nim

`(aconstr Type Expr*)` requires a type

gear3: adds a type for arrayConstr

---

src/gear3/expander.nim
src/nimony/typenav.nim
tests/nimony/sysbasics/tbasics.nif
tests/nimony/sysbasics/tbasics.nim

So that in backend, `array[0..3, int]` is the same as the `array[1..4, int]` and the type of `[1, 2, 3, 4]`

gear3: mangle array types based on length

---

src/nifc/codegen.nim
tests/nimony/sysbasics/ttoplevelvars.nim

nifc: fixes top level var decls with non-literals

---

src/lib/nifindexes.nim
src/nimony/sem.nim
src/nimony/semdata.nim
tests/nifc/hello.expected.idx.nif
tests/nimony/sysbasics/thooks.nif

nimony: implements hook index

---

src/nimony/semdata.nim

Sigmatch imports semdata and semdata imports sigmatch but semdata doesn't use sigmatch, causes problems when compiling semdata or importing it by itself without sigmatch but not when compiling sigmatch or importing it by itself

remove unused cyclic import of sigmatch in semdata

---

src/nifc/codegen.nim
src/nimony/xints.nim

- `inSimpleInit` means a global var initialization. Since the value parts are moved to `InitSection`, `inSimpleInit` should zero.
- `low(int64)` cannot be negated

fixes some issues

---

src/nimony/sem.nim
src/nimony/sigmatch.nim
tests/nimony/generics/texplicitprocinst.nim

closes #269 for now
The difference with original Nim is that for matching symchoices or templates etc, the compiler doesn't try to instantiate them, instead leaving the expression as `(at (symchoice ...) ...)`, only instantiating unambiguous concrete generic procs. This complicates any potential proc type disambiguation logic for overloaded explicit routine instantiations but this seems to not be a priority for now (though I remember something in system using it). Not hard to bring back the old behavior either way.

implement standalone explicit routine instantiations

---

src/nimony/decls.nim
src/nimony/sem.nim
tests/nimony/basics/tgenericbinarytree.nif
tests/nimony/basics/tgenericbinarytree.nim
tests/nimony/generics/trecursiveobj.nim
tests/nimony/sysbasics/tdefault.nif

succeeds #335
The need for this keeps appearing, and the situation might not be as bad as I thought. The issue is that this will break generic structural types used before their declaration (when previously they would be left as `InvokeT` which is soft broken instead), as currently there is no way to tell if a type symbol is forward declared. Forward declared types have fully untyped AST that do not contain typevar symbols, as their typevars are not declared either. So attempting to instantiate this AST fails. Maybe an untyped prepass along with an early declaration of the typevars would solve this, but it's likely that forward declared generic structural types are not that common, so this shouldn't be a blocker. We could also mitigate it by somehow detecting if a type is forward declared …

inline generic structural/alias types

---

lib/std/system.nim
lib/std/system/setimpl.nim
src/gear3/expander.nim
src/nimony/nimony_model.nim
src/nimony/sem.nim
tests/nimony/sysbasics/tdefault.nif

refs #351
Instead of mapping the set type to the respective integer types when it has size 1, 2, 4 or 8, it is always mapped to an array of bytes. Otherwise its implementation would need complex generic code, we could implement this later.
This is not enough to implement sets as set constructors are not lowered. I'm not sure when this would be done, maybe a de-abstraction pass before everything else in gear3? It could maybe be implemented as a compilerproc that takes an array of values (when values are not constant), but this could be too slow. Not using a compilerproc could also optimize over range values.

map set type to uint8 array

---

src/nifc/amd64/emitter.nim
src/nifc/amd64/genasm.nim
src/nifc/amd64/genasm_e.nim
src/nifc/amd64/genasm_s.nim
src/nifc/amd64/machine.nim
src/nifc/amd64/register_allocator.nim
src/nifc/native/analyser.nim

I tried to compile nifc with `nim c -d:enableAsm src/nifc/nifc.nim` to try nifc's native target. But I got compile errors.
In `proc matchAny(c: var Context): bool` in `src/nifc/amd64/emitter.nim`, it seems `result` should be set in `of ParLe:` branch.
But I don't know how `result` should be set, so I just initialized `result` with `false`.
In `proc allocParamWin64*(a: var RegAllocator; param: AsmSlot): Location =` proc in `src/nifc/amd64/machine.nim`,
it seems `result` is assigned in all branches and always initialized but compiler says "Error: Cannot prove that 'result' is initialized.".

Fix compile errors from nifc when asm enabled

---

src/nimony/sem.nim
src/nimony/sembasics.nim
src/nimony/semdata.nim
src/nimony/templates.nim
tests/nimony/basics/tresemtype.nif
tests/nimony/basics/tresemtype.nim

Probably no high priority bugs here, just wanted to lay this out before I forgot about it. If the fixes aren't good enough then this can be closed for now.
Type definitions only semcheck the type bodies if the symbol is freshly declared (an identifier). However in generics and templates, definitions define symbols even if their bodies are not fully checked yet. To deal with this, every symboldef introduced by a template/generic instantiation is marked as "fresh" in the sem context so that type definitions can typecheck their bodies. The way this is done I'm not sure about, it's a set of sym IDs that removes a sym when it's been processed via `handleSymDef`, I don't know if this would leave any symbols remaining. It's not scope sensitive either.
The test does not pass hexer (which is not …

fixes for symbol defs in generics and templates

---

src/hexer/duplifier.nim
src/hexer/expander.nim
src/nimony/derefs.nim
src/nimony/nimony_model.nim
src/nimony/sem.nim
src/nimony/typenav.nim
tests/nimony/basics/tbinarytree.nif
tests/nimony/basics/tgenericbinarytree.nif

Started by inserting derefs but this might be less annoying for ref/ptr objects. Not sure if I adapted hexer behavior correctly.

add tag for dereferencing dot fields

---

src/lib/nifstreams.nim
src/nimony/sem.nim
tests/nimony/basics/t2.nif
tests/nimony/basics/tbinarytree.nif
tests/nimony/basics/tbool.nif
tests/nimony/basics/tcstring.nif
tests/nimony/basics/tdefinedarg.nif
tests/nimony/basics/tdistinct.nif
tests/nimony/basics/tfib2.nif
tests/nimony/basics/tforloop.nif
tests/nimony/basics/tgeneric_obj.nif
tests/nimony/basics/tgenericbinarytree.nif
tests/nimony/basics/trefobject.nif
tests/nimony/basics/tsetter.nif
tests/nimony/basics/ttemplate.nif
tests/nimony/basics/tvarargs.nif
tests/nimony/basics/twhen.nif
tests/nimony/sysbasics/tbasics.nif
tests/nimony/sysbasics/tforloops.nif
tests/nimony/sysbasics/thooks.nif

Previously it would directly copy the magic tag from the declaration of the magic symbol including the declaration line info, when it should be the line info of the use.

give local line info to magics

---

src/nimony/sem.nim

`TypeDeclContext` is used to track if:
* nominal types can be declared, i.e. the type expression is the direct value of a type symbol declaration
* the type `.` is valid, either as `void` for return types or the lack of a constraint for generic params
* the standalone symbols `array`/`range`/`set` can be turned into typeclasses of the respective type, checks for a constraint context but should probably be separated
These are mostly shallow checks, so contexts are no longer propagated in general. The only cases where they're still propagated are:
* `ParX`
* `or`/`and` types, these could also use `InGenericConstraint` or some other typeclass context too
* inlined type symbols (not symbols produced by `semInvoke` which use `InLocalDecl` which could be changed too but in another PR)
The …

make type contexts mostly shallow

---

src/hexer/expander.nim

Given
```nim
proc myFunc(): int {.importc: "myFunc".}
```
It generates
```c
extern NI myFunc/* myFunc.c */(void);
```
Instead of
```c
NI myFunc/* myFunc.c */(void){
}
```

hexer: extern importc functions instead of generating a body

---

.github/workflows/ci.yml
.gitmodules
lib/std/system/mimalloc.nim
src/config.nims
src/hexer/expander.nim
src/hexer/xelim.nim
src/lib/nifindexes.nim
src/nimony/deps.nim
src/nimony/nimony.nim
src/nimony/nimony_model.nim
src/nimony/sem.nim
src/nimony/semdata.nim
src/nimony/semos.nim
tests/nifc/hello.expected.idx.nif
tests/nimony/sysbasics/foo.c
tests/nimony/sysbasics/foo1.c
tests/nimony/sysbasics/tbuild.nim
tests/nimony/sysbasics/tmimalloc.nim

fixes https://github.com/nim-lang/nimony/issues/357
ref https://github.com/microsoft/mimalloc

nimony: implement `build` + mimalloc support

---

src/lib/nifbuilder.nim
src/lib/nifstreams.nim
tests/nimony/nosystem/t2.nif
tests/nimony/nosystem/tbinarytree.nif
tests/nimony/nosystem/tbool.nif
tests/nimony/nosystem/tcstring.nif
tests/nimony/nosystem/tdefinedarg.nif
tests/nimony/nosystem/tdistinct.nif
tests/nimony/nosystem/tenumsizes.nif
tests/nimony/nosystem/tfib2.nif
tests/nimony/nosystem/tforloop.nif
tests/nimony/nosystem/tgeneric_obj.nif
tests/nimony/nosystem/tgenericbinarytree.nif
tests/nimony/nosystem/timportfromexcept.nif
tests/nimony/nosystem/trefobject.nif
tests/nimony/nosystem/tresemtype.nif
tests/nimony/nosystem/tsetter.nif
tests/nimony/nosystem/ttemplate.nif
tests/nimony/nosystem/tvarargs.nif
tests/nimony/nosystem/twhen.nif
tests/nimony/sysbasics/tbasics.nif
tests/nimony/sysbasics/tderefs2.nif
tests/nimony/sysbasics/tdollar.nif
tests/nimony/sysbasics/tforloops.nif
tests/nimony/sysbasics/tforloops1.nif
tests/nimony/sysbasics/thooks.nif
tests/nimony/sysbasics/tresultnoinit.nif

It becomes absolute
```
20,257,lib/std/system.nim
```
https://github.com/nim-lang/nimony/pull/395/commits/14313a84b7df31e146748d141cec5e6fc146e78e

fixes line information is absolute when a filename is present

---

src/nifc/amd64/asm_grammar.nif
src/nifc/amd64/asm_grammar.nim

Emit ".global" directive instead of "global".
All GAS directives has '.' prefix.

Emit .global directive

---

src/nifc/amd64/asm_grammar.nim
src/nifgram/nifgram.nim
tests/data/nifc_grammar.nim

When I compiled nifc with `-d:enableAsm`, got many warnings from `nifc/amd64/asm_grammar.nim`: `Warning: unreachable code after 'return' statement or '{.noReturn.}' proc [UnreachableCode]`.
nifgram.nim generates return or break statement after error proc call but error proc has `{.noreturn.}` pragma and causes many warnings.
This PR fixes nifgram.nim so that it doesn't generate return or break statement after calling error proc.

Fix warnings from nifc/amd64/asm_grammar.nim

---

src/hastur.nim
src/lib/nifindexes.nim
src/nimony/deps.nim
src/nimony/nifconfig.nim
src/nimony/nimony.nim
src/nimony/nimsem.nim
src/nimony/programs.nim
src/nimony/sem.nim
tests/nimony/compat/tstructuralconverter.nim

Followup to #399
Attaches any converter with non-nominal result type to `.` corresponding to `SymId(0)` which is always looked up when matching converters

structural converters in compat mode

---

src/nimony/sem.nim
tests/nimony/nosystem/t2.nif
tests/nimony/nosystem/tdistinct.nif
tests/nimony/nosystem/tgeneric_obj.nif
tests/nimony/nosystem/ttemplate.nif
tests/nimony/nosystem/tvarargs.nif

Was part of a local branch trying to implement statics that stalled, thought it was in master already.
An arbitrary expression in a type context is semchecked as a regular expression. Any expression that has `typedesc` type is considered a proper type and skipped. Otherwise it is considered a value and gives an error if only types are expected in the context.
Since types are usually processed in the signature phase, we need to temporarily change the phase to the bodies phase for the expression to be fully evaluated in the case of calls etc. This is the first time we change to the bodies phase in the codebase so I don't know if it will fully work when a routine is encountered that has not had its body typechecked. Probably won't be an issue until static evaluation.
The typeof/call special …

allow arbitrary type expressions

---

src/nimony/sigmatch.nim

Gets rid of the `leaveLastParRi` mode as it keeps causing bugs. Alternatively can make it an explicit argument. Split from #415

always skip final right paren in linearMatch

---

src/nimony/sem.nim
tests/nimony/errmsgs/tdot.msgs
tests/nimony/errmsgs/tdot.nim
tests/nimony/modules/tfieldviserr.msgs

Every caller to `tryBuiltinDot` builds a call if it fails so any error generated by it is swallowed, and it's enough to produce an error message when the call fails.

don't build error in tryBuiltinDot

---

lib/std/system.nim
lib/std/system/stringimpl.nim
src/hexer/constparams.nim
src/hexer/duplifier.nim
src/hexer/nifcgen.nim
src/hexer/xelim.nim
src/nimony/decls.nim
src/nimony/derefs.nim
src/nimony/sem.nim
tests/nimony/sysbasics/tforloops1.nif

1. `[]` for `ptr UncheckedArray`, just maps to `Pat`, not sure about `UncheckedArray` in general
2. `min`/`max` implementation, needs 2 bugfixes:
3. `not`/`or`/`and` produce `bool` type for their `Item`
4. xelim fixes: trivial `or`/`and` copy to the target and not the dest, locals build their target on the dest and not in their own declaration
Procvar fixes:
5. Generate proc types as named types in nifcgen
6. Allow proc types where `params` types are expected across the codebase and skip to the params (`skipProcTypeToParams`)
Other codegen fixes:
7. Generate call convention pragma for procs and proc types
8. Generate `suf` cstring literals
9. `importc`/`exportc` etc without arguments emit their symbol name as an argument since codegen expects an argument (`CrucialPragma` changes)
Sem …

patches for stringimpl

---

src/nifc/amd64/genasm.nim

It calls itself.
`proc addStrLit*(dest: var TokenBuf; s: string; info = NoLineInfo)` is already defined in `lib/nifcursors.nim`

NIFC: Remove redundant proc

---

lib/std/system.nim
lib/std/system/seqimpl.nim
src/nimony/magics.nim
src/nimony/sem.nim
src/nimony/sigmatch.nim
tests/nimony/nosystem/tfib2.nif
tests/nimony/sysbasics/tforloops1.nif

refs #422
* implements `sink`/`lent`
* similar to #417, instantiate return type of calls in generics but do not instantiate proc, so stuff like `newSeqUninit[T](0)` works
* fix typevars matching invoke types

patches for seqimpl round 1

---

lib/std/system.nim
src/hexer/desugar.nim
src/hexer/nifcgen.nim
src/hexer/pipeline.nim
src/lib/nifcursors.nim
src/nimony/expreval.nim
src/nimony/sigmatch.nim
tests/nimony/sysbasics/tforloops1.nif
tests/nimony/sysbasics/tsets.nim

refs #351, succeeds #415 as described in https://github.com/nim-lang/nimony/pull/415#issuecomment-2615788335
Set types are still only transformed in nifcgen, maybe could generate `dconv` too

generate set ops in desugar pass

---

src/nimony/sem.nim
src/nimony/semdata.nim

This is so we can have more control over the typechecking of `typeof`, `compiles` etc for their special cases in the future (edit: `compiles` doesn't seem to affect semchecking except maybe `compiles do: import ...`?). The analog in the old compiler is the [early evaluation of some magics](https://github.com/nim-lang/Nim/blob/95b1dda1db86881f0119bd319380790fbd594ac5/compiler/semexprs.nim#L2577) before overloading. Maybe we could still walk back error tokens for these magics as `declared`/`defined` already do though.
This is pre-emptive so we could also close it if we don't need it for now.

transform unoverloadable magic calls without typechecking args

---

src/nifc/codegen.nim
src/nifc/genexprs.nim
src/nifc/mangler.nim
src/nifc/typenav.nim
tests/nifc/cimport_array.c.nif
tests/nifc/testcarry.h

Currently, it works only for plain C arrays.
Doesn't work for arrays in C struct field.

NIFC: Implement #423 only for the simplest case

---

src/hexer/nifcgen.nim
src/nimony/nimony_model.nim
src/nimony/sigmatch.nim
tests/nimony/concepts/tadd.nim

1. Make nifcgen not generate concept types or other typeclasses, probably not general enough
2. A constraint type that is a symbol is supposed to be skipped when calling `matchesConstraintAux` (the `f.kind == Symbol` part). This was not done when the matched type is also a symbol type (the `a.kind == Symbol` branch would take over), now it is
tfib and tfib2 also compile with these, they could be moved out of the nosystem category instead

make basic concept test compile

---

lib/std/system.nim
src/hexer/desugar.nim
src/nimony/sem.nim
tests/nimony/sysbasics/tforloops1.nif
tests/nimony/sysbasics/tforloops1.nim

Old system also implements `*=` as [inline proc](https://github.com/nim-lang/Nim/blob/0861dabfa70f40f00c5c95d58c344ad5e0fd19ec/lib/system/arithmetics.nim#L307)

implement inc/dec as inline procs

---

lib/std/system.nim
src/nimony/sem.nim
tests/nimony/nosystem/ttemplate.nif
tests/nimony/sysbasics/tconstarrlen.nif
tests/nimony/sysbasics/tconstarrlen.nim

Implemented as template as opposed to `mLengthArray` magic, this means treating it as a constant value would need `+`/`-` and type conversions to be implemented in expreval.
Required bugfixes:
1. Template bodies use `commonType` on return type (result type of `+`/`-` is `(i +64)` not `(i -1)`)
2. Dot fields of typevars are always treated as nonexistant for UFCS to work
3. Type invocations from normal subscript expressions work properly, including invocations of magic types
4. `low`/`high` give proper return type

implement array len, misc bugfixes

---

src/nimony/deps.nim
src/nimony/nifconfig.nim
src/nimony/nimony.nim
src/nimony/nimsem.nim
src/nimony/sem.nim
src/nimony/semos.nim
tests/nimony/sysbasics/bar.h
tests/nimony/sysbasics/bar1.h
tests/nimony/sysbasics/theader.nim

- add `replaceSubs` helper to `semos.nim` to replace a pattern by an absolute path
- add basic `${path}` and `${nifcache}`support to `{.header.}` + some tests
- add a `-I` of root module path relative to nifcache in final makefile for nim 2.x backwards compatibility (see https://github.com/nim-lang/Nim/pull/10012)
fixes https://github.com/nim-lang/nimony/issues/431

nimony: add basic `${path}` to `{.header.}` for relative c include

---

src/hexer/lifter.nim
src/hexer/nifcgen.nim
src/nimony/nimony_model.nim
src/nimony/sem.nim
src/nimony/sembasics.nim
src/nimony/sigmatch.nim
src/nimony/sizeof.nim
tests/nimony/errmsgs/tbadconverter.msgs
tests/nimony/errmsgs/tbadconverter.nim

Previously the test code would crash from a `wantParRi` due to multiple error nodes being generated
Converters are refactored to register as soon as possible to not generate multiple errors, second `undeclared identifier` error is due to the `(result)` variable type, maybe we can "hide" reuses of error tokens like this somehow.
`declareSym` refactor should also fix quoted ident definitions that aren't procs

attempt to clean up some errors, separate type kind for error types

---

src/nimony/sigmatch.nim
tests/nimony/sysbasics/tintlitmatch.nim

Always considered a conversion match unless the original type is `int`/the equivalent sized int type.
The code is structured like this to prevent writing the conversion branch twice, not sure if it's inefficient

implement int literal matching

---

src/nimony/sigmatch.nim
tests/nimony/sysbasics/tintlitmatch.nif
tests/nimony/sysbasics/tintlitmatch.nim

fixes #477
Supposed to match the old compiler, which reuses `intConvCosts` instead of separate `intLitCosts`. `intConvCosts` seems to mostly exist so a `int32` matches `int` better than `float`. Could rename `intLitCosts` to `literalCosts` if it makes sense to generalize it.
The order of `cmpMatches` had to be reversed into checking the most expensive conversions first, unlike the order in the old compiler `cmpCandidates` because the `equalMatches`/`convMatches` etc in the old compiler complement/are negatives of the costs.

add separate int conv matches

---

src/hexer/desugar.nim
src/hexer/duplifier.nim
src/hexer/nifcgen.nim
src/nifler/bridge.nim
src/nimony/controlflow.nim
src/nimony/enumtostr.nim
src/nimony/expreval.nim
src/nimony/nimony_model.nim
src/nimony/sem.nim
src/nimony/semos.nim
src/nimony/typenav.nim
tests/nimony/nosystem/tbool.nif
tests/nimony/nosystem/tenumsizes.nif
tests/nimony/nosystem/tgeneric_obj.nif
tests/nimony/nosystem/timportfromexcept.nif
tests/nimony/sysbasics/tbasics.nif
tests/nimony/sysbasics/tdollar.nif
tests/nimony/sysbasics/tforloops.nif

Refs #470, empty array/set literals need this to work in hexer.
Not sure if there is a reason why `case of` branches didn't change their selectors from `set` to `ranges` until `nifcgen`, would have had to make them always `curly` here which requires `curly` to be traversed without erroring in the rest of hexer.

separate typed and untyped array/set literals, make case always use `ranges`

---

doc/tags.md
src/hexer/desugar.nim
src/hexer/duplifier.nim
src/hexer/lifter.nim
src/hexer/nifcgen.nim
src/models/nimony_tags.nim
src/models/tags.nim
src/nimony/controlflow.nim
src/nimony/expreval.nim
src/nimony/magics.nim
src/nimony/sem.nim
src/nimony/sigmatch.nim
src/nimony/sizeof.nim
src/nimony/typenav.nim
tests/nimony/nosystem/tgeneric_obj.nif
tests/nimony/sysbasics/tsets.nif

`set` and `sett` were too close to each other and the set type is more common in the output than constructors. Other names would be fine too, we can define alias constants for readability in the compiler

make `set` type tag, constructors now `setconstr`

---

src/nimony/sem.nim

This fixes a part of https://github.com/nim-lang/nimony/issues/432
This PR prints the identifier only when there is an undeclared proc call and an ambiguous call.

Print the identifier when an undeclared proc is called

---

src/nimony/sem.nim
tests/nimony/sysbasics/tdefault.nim

1. `firstField` of empty object types is `.`, not `)`, has to be checked before iterating
2. For calls with no arguments being handled as object constructors, checking that the callee is a type symbol does not handle the case where it is a generic invocation i.e. `Foo[int]()`, so a type of `TypedescT` is checked instead same as for conversions

fix empty object constructors

---

src/nifler/bridge.nim
tests/hexer/gear3_helloworld.nif
tests/nimony/nosystem/tsetter.nif
tests/nimony/nosystem/tvarargs.nif

`nkIteratorTy` handled the same as `nkProcTy`, has updated tag along with `nkOutTy` and `nkStaticTy` (only used in old concepts), `nkStaticStmt` changed to `staticstmt` instead of `static`

nifler: make nkEmpty opt in, fix some type tags

---

src/hexer/nifcgen.nim

This PR calculates column and line number in the same way as `toString` proc in `lib/nifstreams.nim`.

Fix #497: Generate correct line info when include statement is used

---

src/nifc/cprelude.nim

It is also suppressed in the Nim
```c
nifcache/sys9azlf.c:312:3: warning: switch condition has boolean value [-Wswitch-bool]
312 |   switch (e_0){
```

nifc: suppresses `-Wswitch-bool` warnings

---

src/hexer/iterinliner.nim
src/hexer/nifcgen.nim
src/nimony/sem.nim

The issues in sem were: Dot and tuple field names could be quoted/symchoice trees, object constructor types could be `InvokeT` trees if they have generic parameters.

fix issues with `add` for cursor

---

src/hexer/desugar.nim
src/hexer/nifcgen.nim
src/nimony/sem.nim
src/nimony/sembasics.nim
src/nimony/semdata.nim
src/nimony/sigmatch.nim
tests/nimony/generics/temptyliteral.nim

refs #470
* When semchecking call arguments, empty array/set literals without an inferred element type are allowed to compile and produce the type `auto`
* Expressions with type `auto` are detected in sigmatch and checked for being empty literals. If so, the param type is checked to be a matching array/set type and the literal is updated to have the param type. If the param type is generic, the match is marked as containing a generic empty literal.
* Then when the call matches, it is checked if the match was marked to contain a generic empty literal, in which case empty literal arguments instantiate their type when being added to the final call node.

implement empty array/set literal matching

---

lib/std/syncio.nim

`nil ptr UncheckedArray[uint8]` causes compile error because `nil ptr T` is not implemented yet.

Remove nil ptr T from lib/std/syncio.nim

---

src/nimony/sem.nim
src/nimony/sembasics.nim
tests/nimony/lookups/deps/mambtype1.nim
tests/nimony/lookups/deps/mambtype2.nim
tests/nimony/lookups/tambtype.msgs
tests/nimony/lookups/tambtype.nim
tests/nimony/lookups/tambtypeconv.msgs
tests/nimony/lookups/tambtypeconv.nim
tests/nimony/lookups/tlocalcall.nim
tests/nimony/lookups/tscopedtype.nim

Overload lookup is changed to match the old compiler: Callee symbols no longer use `FindAll`, they use a new lookup mode `FindOverloads`, which only considers overloads of unambiguous symbols if they are overloadable. `InnerMost` always returns a symbol if it is unambiguous, even if it is overloadable. (before `InnerMost` behaved like `FindOverloads`)
This means callee symbols prefer local unambiguous symbols to outer overloads. To deal with this when the local symbols are not procs (i.e. `let len = arr.len`), in the case where the callee symbol is not callable, all overloads are considered.
For this to work, symchoice callees now ignore non-callable symbols and give an error if none of the choices were callable (the previous error would have been "undeclared identifier").
This also means …

overload lookup fixes

---

src/hexer/duplifier.nim
src/hexer/mover.nim
src/hexer/pipeline.nim

Integrate the move analyser into duplifier.nim

---

src/hexer/desugar.nim
src/hexer/nifcgen.nim
src/nimony/expreval.nim
src/nimony/sem.nim
tests/nimony/errmsgs/tbadrange.msgs
tests/nimony/errmsgs/tbadrange.nim
tests/nimony/generics/temptyliteral.nim
tests/nimony/nosystem/tgeneric_obj.nif
tests/nimony/nosystem/trangeexprtype.nim

Range/array type invocations with `..` expressions were broken without a `..` overload defined, as the args would be typechecked first and produce an error token, fixed here by handling magic invocations immediately.

clean up magic invocations, fix range types

---

src/nimony/sigmatch.nim
tests/nimony/errmsgs/tunderspecifiedgeneric.msgs
tests/nimony/errmsgs/tunderspecifiedgeneric.nim

Call to `error0` would reset the match object

fix typevar error info in sigmatch

---

src/hexer/mover.nim
src/nimony/derefs.nim

Originally encountered the `PatX` case in `validBorrowsFrom`, which is needed for things like var returns to `s.data[i]`.

add PatX, TupAtX to missing spots in derefs, mover

---

src/nimony/sem.nim
src/nimony/sigmatch.nim
tests/nimony/generics/deps/mgenericproc.nim
tests/nimony/generics/texplicitprocinst.nif
tests/nimony/generics/texplicitprocinst.nim

`matchTypevars` only builds the `tvars` and `inferred` tables, `m.typeArgs` still has to be built after the match because it is used in `requestRoutineInstance` for the proc signature lookup key (and to build the invoke node in the signature AST but this is rebuilt in the final instantiated routine).

build typeArgs for explicit generics

---

src/nimony/sem.nim
tests/nimony/generics/texplicitprocinst.nif

follows up #566
The `inferred` table passed to `requestRoutineInstance` is added to global memory, hence every type cursor included in it also has to be in global memory. To ensure this, we rebuild the cursors from the added invocation node in the signature, so that the cursors live as long as the signature does.
Another way might be to ensure everything saved to `inferred` in sigmatch passes through `typeToCursor`, but maybe this would be slower.

build inst request binding cursors from signature invocation

---

src/nimony/sem.nim
src/nimony/semdata.nim
tests/nimony/modules/deps/mfieldvis.nim
tests/nimony/modules/tfieldviserr.nim
tests/nimony/modules/tfieldvisworking.nim

fixes #563
`inGenericInst` as described in https://github.com/nim-lang/nimony/issues/563#issuecomment-2662784550 is generalized to `inInst` to include template instantiations, and this way of doing it in `semGenericParams` happens to include type instantiations which is hopefully fine.
Explicit generic calls in generic/template contexts now rebuild the explicit instantiation after matching since they cannot instantiate it fully, previously they would just leave the sym node of the generic proc and the generic params would have to be inferred from the args on resem.
Type instantiations now temporarily change their scope to the top level scope for exported fields to work when creating an instantiation in a scope. Not sure if this is a hack.

skip field visibility on resem and fix some generics issues

---

src/hexer/nifcgen.nim

Don't add `imp` when `importSymbol` was called with a proc symbol with header pragma or any other symbols that doesn't need to be added.

fixes #556

---

src/hexer/duplifier.nim

`trOnlyEssentials` is called for `nodestroy` procs which previously did not track local declarations to cache the types of locals, this is now done.

register local types with `nodestroy` in duplifier

---

src/nimony/sem.nim
src/nimony/semdata.nim
tests/nimony/nosystem/tgenericbinarytree.nif

refs #543
The list of type instantiation syms which need their declarations appended to a module is now separated from the mapping of canonical invocations to their instantiated values. Only types which are fully instantiated i.e. without their generic arguments containing generic parameters themselves are appended to the module.
This allows us to cache partially instantiated types in `instantiatedTypes`, i.e. `Foo[U]` where `U` is a generic parameter of the current context now only substitutes the body of `Foo` with `U` once rather than every time `Foo[U]` is invoked. Maybe these shouldn't generate syms either but idk if it would be worth it to try to change that.
This would also allow us to repeatedly alternate over iterating the type instantiation requests and the proc instantiation …

split type inst cache and module type inst declaration list

---

lib/std/syncio.nim

Workaround https://github.com/nim-lang/nimony/issues/573 by replacing the untyped template parameter to `bool`.
This still fail to compile due to https://github.com/nim-lang/nimony/issues/575 .
(`addReadLine` proc uses `..<` iterator under the while loop)

Fix compile errors in syncio module

---

src/hexer/nifcgen.nim

Don't generate `imp` when importing variables with header pragma.

fixes #583

---

src/nimony/sem.nim
tests/nimony/generics/taddobj.nim
tests/nimony/generics/tobjfield.nim

fixes #543
The aim with #580 was to instantiate these fully in `semInvoke` then look up the impls from `instantiatedTypes` with the canon type of the invoke types, but we can't do this yet because of the problems with instantiating forward declared types.
Instead `findObjField` and `buildDefaultObjConstr` now accept/build bindings based on invocation type args and instantiate the final field type with them. They rebuild bindings for parent types as well when iterating over them, substituting their arguments with the existing bindings.

instantiate field types of invocation object types in exprs

---

src/nimony/sigmatch.nim
tests/nimony/generics/texplicitprocinst.nif
tests/nimony/generics/twronginference.msgs
tests/nimony/generics/twronginference.nim
tests/nimony/nosystem/tfib2.nif
tests/nimony/sysbasics/tdefaultparams.nif

The current `sigmatch.commonType` just accepts any type for the rematch which can cause invalid matches. The rematch can be a conversion match as well which is not trivial to handle in `commonType`. So this is changed to just recurse over `singleArgImpl` same as how `linearMatch` recurses over itself. This does not give the `InvalidRematch` error message though, instead giving a normal match error.

match directly to inferred value of generic param

---

src/hexer/nifcgen.nim
tests/nimony/modules/deps/mstringuse.nim
tests/nimony/modules/timportedstringuse.nim

Any case where the only occurence of the string type in a module was in a string literal would fail without this, caught from `discard "..."` but another case might be a call to a proc from another module with a string literal argument

import string type symbol for string literals in nifcgen

---

src/hexer/nifcgen.nim
tests/nimony/modules/deps/mprocvar.nim
tests/nimony/modules/timportedprocvar.nim

Declarations of named structural types i.e. arrays, procs etc are appended to `e.pending` in `traverseAsNamedType`. Since this can also occur when traversing types of imported symbols, the pending buffer is now flushed after the imported symbols are processed.

nifcgen: add pending named types after imported symbols

---

doc/tags.md
src/hexer/nifcgen.nim
src/models/nimony_tags.nim
src/nimony/sem.nim
src/nimony/semuntyped.nim
tests/nimony/compat/tgenericproc.nim
tests/nimony/compat/ttemplate.nim

Unimplemented stuff etc can break these tests when new templates/generic procs are added to system, we can hold off on maintaining them until the feature is finished.

make compat untyped templates/generics opt in via pragma for now

---

src/hexer/nifcgen.nim
src/nifc/codegen.nim
src/nifc/cprelude.nim
tests/nimony/sysbasics/tbasics.nif
tests/nimony/sysbasics/tbasics.nim

It implements `nimcall` following the fashion of Nim. So it won't cause warnings on unsupported platforms. And it won't be treated as `NoCallConv` when used for functions.
Otherwise, it causes warnings on macOS: `warning: 'fastcall' calling convention is not supported for this target [-Wignored-attributes]` for `nimcall` which is quite commonly used

fixes `nimcall`

---

lib/std/strutils.nim

parseopt uses `proc `$`*(x: char): string`.
`substr` is defined in `lib/std/system/stringimpl.nim` and using `substr` causes ambiguous call error.

Add $ proc and remove substr from strutils

---

src/hexer/nifcgen.nim
src/nifc/gentypes.nim
src/nifc/nifc_model.nim
tests/nimony/modules/deps/menumiter.nim
tests/nimony/modules/tenumiter.nim

fixes #617
Imported enum fields in nifcgen queue the full enum type to be imported rather than attempting to generate an extern declaration for the enum field.
Enum types used before their declarations in object fields in nifc is also fixed: previously they were considered structural and so not added to `e.ordered` which would generate the object type first if it was encountered first. Now they are always added to `e.ordered`, since they do not depend on other types it should be safe to generate them as early as they are encountered. Proc types are also not handled here but I don't know what would be done for them.
Sorry for abrupt PR, figured it would be more effort to explain this than to do it

fix enum imports in nifcgen and forward uses in nifc

---

src/lib/nifcursors.nim
src/nifler/bridge.nim
src/nimony/sem.nim
src/nimony/sigmatch.nim
tests/nimony/lookups/tlocalcall.nim
tests/nimony/nosystem/twhen.nim
tests/nimony/sysbasics/tdefinedwhen.nif
tests/nimony/sysbasics/tdefinedwhen.nim
tests/nimony/sysbasics/tindex.nim

The test in `tlocalcall` is enabled but with an explicit `proc ()` annotation as otherwise its type gets inferred to `ParamsT` without the return type, so in the AST it becomes `(let foo . . (params ...) bar)`, so the return type of `foo` is skipped from the `params` to `bar` and so the type of `foo(123)` becomes literally `bar`. In any case the `proc ()` annotation has worked in other places for a while now.
A small fix is needed in sigmatch for proc types with empty pragmas to work: `skipToEnd` is called before `inc` which is supposed to skip the `ParRi`, but `skipToEnd` already skips the `ParRi`, so a new `skipUntilEnd` is added which doesn't skip it. Also `nkEmpty` params and pragmas for proc types in nifler are now allowed to generate `.`.
The disabled `when defined` tests in `twhen` …

enable some tests, fix sigmatch for proc types

---

src/hexer/iterinliner.nim
tests/nimony/sysbasics/tforloops1.nif
tests/nimony/sysbasics/tforloops1.nim
tests/nimony/sysbasics/tforloops1.output

fixes #633 
This PR instantiates each `symdefs` in the iterator with a different id.

fixes #633; instantiates for loops defs

---

src/nifc/codegen.nim

Change type of `cmdLine` in generated C code so that parseopt module can import it as `ptr UncheckedArray[cstring]`.

Fix C compile error from lib/std/parseopt.nim

---

lib/std/syncio.nim

`writeLine` proc in `lib/std/syncio.nim` has `f: var File` parameter.
```nim
proc writeLine*(f: var File; s: string) =
```
`writeLine stdout, "foo"` is compiled to C code `writeLine_0_syn1lfpjv((&stdout),`.
But `&stdout` causes compile error in MinGW: `error: lvalue required as unary '&' operand`

Fix compile error from MinGW

---

src/nimony/sem.nim
tests/nimony/errmsgs/tcommontype.msgs
tests/nimony/errmsgs/tcommontype.nim
tests/nimony/lookups/tambtype.msgs

refs #649
Unsure if this is the same memory corruption mentioned in the issue but `it.n` in this case is skipped beyond the ParRi by `semAddr` by the time it calls `commonType` which gives it a random, potentially invalid line info for some reason

fix commonType line info

---

tests/nimony/stdlib/tparseopt.nim

As hastur doesn't pass arguments to test programs, this test code modify `cmdCount` and `cmdLine` to set arguments to test.

adds tests for parseopt module

---

lib/std/system.nim
src/nimony/sigmatch.nim
tests/nimony/overload/tinvariantmatch.nim
tests/nimony/sysbasics/tseqs.nim

closes #646
This makes `linearMatch` more a way of matching types invariantly to each other rather than just a check for tree equality that also considers typevars. Maybe `linearMatch` is not the best implementation for this but it's the expected behavior from `linearMatch` in the places where it's used.
For integral types, bits are now normalized, so `ptr int` now matches `ptr int64`. Edit: This is now disabled for `typedesc`, i.e. `typedesc[int]` and `typedesc[int64]` are considered different. In original Nim they match each other, they just match the equal versions better, but I remember this not being intended.
For procs, `procTypeMatch` is called directly since it currently basically checks for equality, but in the future if stuff like convertibility from `nimcall` to `closure` is …

make linearMatch aware of special cases

---

src/hexer/iterinliner.nim
src/hexer/lifter.nim
src/hexer/nifcgen.nim
src/hexer/typekeys.nim
src/nifler/bridge.nim
src/nimony/decls.nim
src/nimony/sem.nim
src/nimony/sigmatch.nim
src/nimony/sizeof.nim
src/nimony/typenav.nim
tests/nimony/generics/ttuplecache.nif
tests/nimony/generics/ttuplecache.nim
tests/nimony/sysbasics/tbasics.nif
tests/nimony/sysbasics/tforloops.nif

fixes #692
Fields of named tuple types now have the representation `(kv name type)` where the name is an identifier rather than a symbol. Tuple types without field names now just have types themselves as the fields rather than anonymous `FieldN` fields.
Alternative representations are always generating a `kv` but with `.` or the old `FieldN` as the name, or adding a new tag like `(tfld)` that could also contain pragmas if we want them.

use `kv` with ident instead of `fld` for named tuple types, make it optional

---

src/nimony/sigmatch.nim
tests/nimony/generics/targgenericrematch.nim

fixes #693
When matching to the inferred value of a typevar, do not consider typevar types inside it as types that need to be inferred/compared against inferred values, instead just check that the matched type matches the constraint of the typevar (as opposed to checking for equality as in #536). Types provided from the outside environment should have no effect on the inferences of the current match.
Previously I thought the typevar matching could have been restricted in some other way, like only inferring to typevars belonging to the routine of the current match. But this would not handle the case when the routine is a recursive generic routine, as it would be valid to infer a typevar to itself.

treat inferred types containing generic params as concrete

---

src/nimony/sem.nim
src/nimony/sembasics.nim
src/nimony/semdata.nim

fixes #613, tested locally
`unoverloadableMagics` is reused but could use a different method as well

ignore `defined` etc argument errors in debug mode

---

src/gear2/modnames.nim
src/hexer/nifcgen.nim
src/lib/symparser.nim
src/nimony/sem.nim
src/nimony/sigmatch.nim
tests/nimony/generics/deps/mexternalinst1.nim
tests/nimony/generics/deps/mexternalinst2_0.nim
tests/nimony/generics/deps/mexternalinst2_1.nim
tests/nimony/generics/deps/mexternalinst2_2.nim
tests/nimony/generics/texternalinst1.nim
tests/nimony/generics/texternalinst2.nim
tests/nimony/generics/ttuplecache.nif
tests/nimony/generics/twronginference.msgs
tests/nimony/modules/tfieldviserr.msgs
tests/nimony/nosystem/tgeneric_obj.nif
tests/nimony/nosystem/tgenericbinarytree.nif
tests/nimony/nosystem/ttemplate.nif
tests/nimony/sysbasics/temptyseq.nif
tests/nimony/sysbasics/thooks.nif
tests/nimony/sysbasics/trefobject.nif

fixes #715, supersedes #724
The scheme is:
```
abc.123.origmod.Iabcdefgh.instmod
```
where `abcdefgh` is the encoded hash of the invocation NIF string (`typeToCanon` depends on runtime literal IDs). The first 3 parts are the same as the original symbol. But the original symbol being preserved isn't necessary, it can be included in the hash, so we could have something as bare as:
```
abc.Iabcdefgh.instmod
```
or any other arrangement in between if the current one is too ugly.
The final `.instmod` part is ignored both in `sigmatch` for comparisons, and removed in the NIFC output by hexer, so that the type is generated under the same name. The scheme also applies to any symbol declared inside instantiations so that fields are the same across instantiations too.
I also tried including proc …

special symbol scheme for type instantiations

---

src/nifc/gentypes.nim

This PR produces code like this:
```c
typedef struct array array;
typedef struct seq{
int len;
array* data;}
seq;
typedef struct array {
int a[1];}
array;
```
This compiles without error with gcc 14.2 and clang 19.1.0:
https://godbolt.org/z/5Yf3Wa6h8
https://godbolt.org/z/Yo19ba9c3
But fails to compile with gcc 4.5.3 and clang 3.5.2 and older:
https://godbolt.org/z/KWz8MG4ha
https://godbolt.org/z/Krq9Prjev
If it must be compiled without error with older gcc and clang, `array` must be defined without `typedef` if it is forward declared like this:
```c
typedef struct array array;
typedef struct seq{
int len;
array* data;}
seq;
struct array {
int a[1];};
```
https://godbolt.org/z/dY9ncvYW4
https://godbolt.org/z/GfT6aK53a
Checking if it is forward declared and changing how to generate C array …

fixes #691

---

src/nimony/sigmatch.nim
tests/nimony/overload/tgenericdisamb.nim
tests/nimony/overload/tgenericdisamb.output

closes #647
The params of the callees are matched against each other, to check if they match either as a generic match and the other one doesn't. I don't exactly know why only generic matches are counted in the original compiler and not also equal matches as in the case of `var T` matching `T` (though the vice versa also matches for now so this wouldn't disambiguate it yet). To get `var T` disambiguation we also need the specificity counter method but that can be done in a followup.

implement mutual generic disambiguation

---

lib/std/tables.nim
tests/nimony/stdlib/ttables.nim

Some tests are disabled as adding two keys to table causes error: https://github.com/nim-lang/nimony/issues/741
`pairs` iterator doesn't work

fixes tables to compile and adds test

---

src/nifc/typenav.nim
tests/nimony/sysbasics/tarrays.nim

fixes #745
```
(gvar :a.0.tes3wd9hn1 . 8 AarrayAR0AiS-1ZS1ZS1.0.t 29
(aconstr ~21 AarrayAR0AiS-1ZS1ZS1.0.t 1
(aconstr AarrayAiS-1ZS1.0.t 1 +0))) 4,105,lib/std/syncio.nim
(call write.2.syn1lfpjv 6 stdout.c 5,4,test4.nim
(at
(at a.0.tes3wd9hn1 2 +0) 5 +0)) 2,106,lib/std/syncio.nim
(type :AarrayAR0AiS-1ZS1ZS1.0.t .
(array 9 AarrayAiS-1ZS1.0.t +1)))
```
In `AtC`, `getTypeImpl` returns the type of the firstSon of the construct, which means the type of a variable. Because array types exist in the form of alises. We need to skip it

nifc: fixes #745; fixes getType of `AtC`

---

src/nimony/sem.nim
src/nimony/semuntyped.nim
tests/nimony/nosystem/tgeneric_obj.nif
tests/nimony/nosystem/ttemplate.nif
tests/nimony/sysbasics/trefobject.nif
tests/nimony/sysbasics/trefobject.nim

closes #645
The untyped mode in this case leaves everything except the generic params (given they were not shadowed) as identifiers, i.e. only the typevars are captured, since not every symbol in the module is processed yet.

declare typevars and use untyped prepass for generic forward decls

---

src/nimony/deps.nim
src/nimony/nifconfig.nim

This PR generates a file with `NifConfig` in the cache directory.
When the command line option changed, content of the file is updated and `*.2.idx.nif` and `*.2.nif` files are updated.

fixes #716; generates a file contains options

---

src/nimony/programs.nim
src/nimony/sem.nim
src/nimony/semdata.nim
tests/nimony/modules/tmultipleimport.nim

Previously the first import of a module would be the only one considered. Now they are additive. The idea is that a module being imported and another module exporting symbols from it do not clash with each other but I'm not sure if this fix is needed for that. In any case silently doing nothing on a consecutive import is not good.

fix consecutive imports to the same module

---

src/hexer/nifcgen.nim
src/nimony/builtintypes.nim
src/nimony/expreval.nim
src/nimony/renderer.nim
src/nimony/sem.nim
src/nimony/sigmatch.nim
src/nimony/typenav.nim
tests/nimony/stdlib/ttables.nim

`semConstExpr` now fits the evaluated constant value to an expression matching the type of the constant. Though `semConstExpr` is only used for the values of `const` declarations which is still disabled and can be enabled in another PR after this one (it requires some test changes).
A new suffix `"C"` is added for cstring literals, previously `"R"` was used for cstring literals in expreval which is wrong, it is used for raw string literals.

implement annotating constant types, fix cstring literals

---

lib/std/system/seqimpl.nim
src/nimony/sigmatch.nim
tests/nimony/sysbasics/tseqs.nim

`toOpenArray` call is changed to an object constructor to `openArray` since there is no overload of `toOpenArray` that takes a `ptr UncheckedArray` and a length parameter. In the original system the `toOpenArray` overload does not take a length, instead it takes a first index and a last index, so I didn't add an overload named as such here. Could still add a `toOpenArrayLen` overload that could be exported.
For generic disambiguation to work between `default(seq[T])` and `default(T: object)`, `T: object` did not match `seq[T]` because the `(typekind)` typeclass did not skip invocation types to their base type, this is now fixed

enable seq openarray converter, test default, fix `(typekind)` for invocations

---

lib/std/system/stringimpl.nim
tests/nimony/sysbasics/tstrings.nim

`newLen` could be smaller or equal than `cap`, but the other branch is empty. It needs to update the length

fixes strings forgot to update the newLen

---

src/nimony/sem.nim
src/nimony/sigmatch.nim
tests/nimony/overload/tnamedparams.nif
tests/nimony/overload/tnamedparams.nim

closes #522
When encountering a named argument in a call, sem semchecks its value and passes it along with the name to sigmatch. It is also tracked if a named argument was given, in which case the arguments are reordered before passing to the `sigmatch` proc.
The way the reordering is done: The signature params are iterated over first to build a table of names to param positions etc. Then the given arguments are iterated over, saving the positions of arguments belonging to each parameter. Then a new list of arguments is built in the order of the parameters. Varargs is considered by saving arguments as "continued", i.e. the parameter position is not advanced for them when building the list. Missing parameters add a dot token to mark a default value, but this does not fail early to behave …

implement named args

---

src/hexer/iterinliner.nim
src/nimony/sem.nim
src/nimony/sigmatch.nim
tests/nimony/concepts/tconceptiterator.nim
tests/nimony/nosystem/tfib2.nif

fixes #829
Instead of `ConceptProcY` `FnCandidate` tracks if the routine came from a concept and uses the same routine kind as declared in the concept.
Also routine symbols of concepts in toplevel scope also declare their symbols as global so that their generic parameters can be loaded in sigmatch if they have any.
iterinliner also no longer transforms generic routines.

allow any routine kind in concepts, fix concepts in other modules

---

src/hexer/iterinliner.nim

Values passed to the iterator can be modified by referencing it with cursor.
But probably it should use cursor only when it is safe to use it.
It should use cursor only when the argument is lvalue?

fixes #823

---

src/nimony/sem.nim
src/nimony/sigmatch.nim
tests/nimony/calls/ttemplatecalltype1.nim
tests/nimony/calls/ttemplatecalltype2.msgs
tests/nimony/calls/ttemplatecalltype2.nim
tests/nimony/nosystem/tcstring.nif
tests/nimony/sysbasics/tconstarrlen.nif
tests/nimony/sysbasics/temptyseq.nif
tests/nimony/sysbasics/tforloops1.nif

follows up #844
After the expanded template body is semchecked, it is matched to the return type first (`untyped` is special cased to not do anything as in `semProcBody` but maybe it can be handled generally in `commonType`), then matched to the expected type of the expression.
Sigmatch now skips `(expr)` etc when matching int and string literals. This is not done yet for empty collection literals since they manipulate the AST instead of just prepending to it but it's not hard to do.

match instantiated template bodies to return types, required fixes

---

src/nimony/sigmatch.nim

split from #848
1. or/and types did not always skip f on failure of matchesConstraint, just added separate variable for it
2. T: Ordinal now matches another Ordinal typevar

fix and/or, ordinal typeclasses

---

src/nimony/sem.nim
tests/nimony/sysbasics/tlentboolif.nim

fixes #853
I must have missed it since `semConstBoolExpr` below already skips modifier

skip modifier in semBoolExpr

---

src/nimony/sem.nim
tests/nimony/generics/ttuplecache.nif
tests/nimony/nosystem/t2.nif
tests/nimony/nosystem/ttemplate.nif
tests/nimony/sysbasics/tbasics.nif
tests/nimony/sysbasics/tconstarrlen.nif
tests/nimony/sysbasics/temptyseq.nif
tests/nimony/sysbasics/tforloops1.nif

This removes half of the `(expr (expr ...))` generated by template calls. The other (expr) is because the `(stmts)` part of template body is directly used when instantiating templates and semchecks to `(expr)`.

don't generate (expr) for routine expression returns

---

src/hexer/nifcgen.nim
tests/nimony/sysbasics/tsets.nif
tests/nimony/sysbasics/tsets.nim

fixes #873
adds a temp for `c.pending` because of nested scopes

fixes #873; set constructor in proc in block statement causes error 

---

lib/std/syncio.nim
tests/nimony/stdlib/tsyncio.nim
tests/nimony/stdlib/tsyncio.output
tests/nimony/sysbasics/tbasics.nif
tests/nimony/sysbasics/tforloops1.nif
tests/nimony/sysbasics/tsets.nif

- change `writeBuffer` argument type to `pointer` to make it generic like `copyMem` and compat with nim 2.x
- add a test for `writeBuffer` (also it's another test for pointer and sizeof)

syncio: use `pointer` type for `writeBuffer`

---

lib/std/system.nim
src/nimony/sem.nim
tests/contracts/tbasics.msgs
tests/nimony/stdlib/tsyncio.nim
tests/nimony/sysbasics/tconstarrlen.nif
tests/nimony/sysbasics/tforloops1.nif

fixes #878
fixes  #879
```nim
proc sizeof*(x: typedesc): int {.magic: "SizeOf", noSideEffect.}
```
Without the typevar `T`, it seems to have some bugs on overloading

semcheck`sizeof` and adds a template overload for `sizeof`

---

lib/std/system.nim

`in` operator is used in https://github.com/nim-lang/nimony/issues/875

adds `in` operator

---

src/nimony/sem.nim
src/nimony/templates.nim
tests/nimony/templates/tinvalidrecursion.msgs
tests/nimony/templates/tinvalidrecursion.nim

When typechecking the body of a template, if it calls itself, it will try to expand it based on the body of the prototype, which is `.`. Calling `semExpr` on this gives an "expression expected" error with no line info. So attempting to expand a template with body `.` now directly gives an error.
This is not to say that template recursions are always invalid but they should probably only be allowed in untyped contexts as they may add symbols to scope etc.

error for recursions in typed templates

---

lib/std/system/comparisons.nim
src/nimony/sigmatch.nim
src/nimony/typenav.nim
tests/nimony/stdlib/tsystem.nim

1. generic min/max
2. minor bug in sigmatch
3. consider derefs of `lent` types in `getType`

misc fixes extracted from #908

---

.github/workflows/ci.yml
src/hastur.nim

The dependency is broken, apparently windows-2025 and above do not need it anyway since winget can be installed without any dependencies

disable winget install dependency, use windows-2025

---

.github/workflows/ci.yml

For some reason `winget upgrade` gives an error exit code if the latest version was already installed, guessing this is related to the cache. Could not find a way to make winget itself not produce an error exit code for this. Another option might be to not upgrade at all.

ignore winget upgrade error when on latest version

---

lib/std/system/arithmetics.nim
lib/std/system/basic_types.nim
src/nimony/sigmatch.nim
tests/nimony/overload/ttypeclasses.nim

closes #675
When matching against a constraint, if the constraint type is not found to be a typeclass, it is matched like a regular type. `linearMatch` is used for this, which for now means conversions from the argument to the constraint type are not allowed (i.e. `"abc"` matching `T: cstring` or `1'i8` matching `T: int`) which is a difference from original Nim (it would also need to infer the typevar to the *converted* type and not the argument type, not to mention considering converters etc).
This is done so that `SomeInteger` can now be implemented as intended and used for `shl`/`shr` etc. However implicit generics are not implemented so the signatures use an explicit generic parameter for it.
To make the call to `linearMatch` here less hacky, `m.err` now just tracks if the match …

match concrete types in constraints

---

lib/std/formatfloat.nim

I'm trying to use `src/lib/nifbuilder.nim` to implement [toNif stdlib API](https://github.com/nim-lang/nimony/issues/902).
nifbuilder imports formatfloat and math modules but they are not yet implemented.
And it seems current stdlib can write floats as strings to files using `fprintf` with syncio but cannot convert floats to strings.

adds formatfloat module

---

lib/std/math.nim
tests/nimony/stdlib/tmath.nim

nifbuilder uses `classify` in math module.

adds signbit and classify in math module

---

src/hexer/pipeline.nim
src/hexer/xelim.nim
tests/nimony/arc/taddstr.nim

`injectDups` won't work properly without transforming if expressions (i.e. lowerExprs). Otherwise, we need to treat `if` differently in `injectDups` instead of handling it like statements, which causes double free

fixes return if expr: lowerExprs before injectDups

---

src/nimony/derefs.nim
tests/nimony/arc/tsink_string.nim

fixes #954
`sink parameter` can be modified

fixes #954; move sink parameter causes compile error

---

lib/std/system.nim
tests/nimony/const/tconstarrlen.nif
tests/nimony/iter/tforloops1.nif
tests/nimony/sysbasics/tdollarints.nim

It is used to implement `proc toNif(b: var NifBuilder; x: bool)`.

adds $ for bools

---

src/nimony/sem.nim
src/nimony/sigmatch.nim
tests/nimony/generics/tgenerictypeconstraints.msgs
tests/nimony/generics/tgenerictypeconstraints.nim

Type invocations like `Foo[int]` now check constraints. `matchesConstraint` is reused from sigmatch, probably this will reuse `static` handling when implemented as well.

implement constraints for type generic params

---

src/nimony/sem.nim
tests/nimony/iter/timplicititems.nim

Behaves as in [original Nim](https://github.com/nim-lang/Nim/blob/d4098e6ca031aba9825980f9a17d3b54a9990577/compiler/semstmts.nim#L1297-L1305): whether to use `items` or `pairs` is decided by the number of variables not wrapped in `()`, and the error for the overloads is kept. I expected the original compiler to restrict the overloads to `iterator` symbols but it doesn't.
The iterator call check (which has to be performed again here) now makes sure the produced expression is a call. The problem with checking for identifiers for concepts is it could be a proc call from a concept and not an iterator. Maybe we could fix this and make the check easier by producing a different tag like `IcallX` for iterator calls or wrapping the call in it, this might help with things like typechecking `toSeq` …

implement implicit items/pairs iterators

---

src/nimony/sem.nim
tests/nimony/when/deps/mfoo.nim
tests/nimony/when/twhenimport.nim

fixes #966, split from #931
`when` statements were restricted to the semchecking bodies compilation phase, now it is processed as early as the signature phase, so that types can use symbols imported/defined in `when` branches.
Toplevel syms phase still does not process `when` statements for now so symbols declared in them can't be used before they are declared. The reason is that the conditions might not compile in this phase, especially in the system module where stuff like `true` will not be defined yet, or constants in the same module in general. We can either develop the toplevel syms phase so that these will work or figure out how to decide when to delay the `when` statement depending on the condition expression.

process `when` in signature phase

---

lib/std/syncio.nim
lib/std/system/basic_types.nim
lib/std/system/comparisons.nim
lib/std/system/defaults.nim
src/lib/nifbuilder.nim
src/nifler/bridge.nim
src/nimony/magics.nim
src/nimony/sem.nim
tests/nimony/enums/tostring.nim
tests/nimony/iter/tforloops1.nif
tests/nimony/sets/tsets.nif
tests/nimony/sysbasics/tbasics.nif
tests/nimony/sysbasics/temptyseq.nif
tests/nimony/sysbasics/tintlitmatch.nif

refs #968, closes #952
`enum` is split into 2 typeclasses: `OrdinalEnum` and `HoleyEnum`, which compile to `(typekind (enum))` and `(typekind (holeyenum))`. For simplicity, what previously parsed as the `enum` typeclass now parses as an identifier `enum` which is defined in system as `OrdinalEnum | HoleyEnum`.
However since `or` types cannot match themselves yet (#931), some overloads for `enum` have to be temporarily split into overloads for `OrdinalEnum` and `HoleyEnum`. The overloads for `==`, `<` etc though are split so that generic disambiguation works since they are also defined for `Ordinal`: `Ordinal` can be disambiguated with `OrdinalEnum` since `OrdinalEnum` matches `Ordinal` but not vice versa, however it cannot be disambiguated with `enum` in general since neither typeclass …

split `enum` typeclass into ordinal and holey type kinds

---

lib/std/system/defaults.nim
tests/nimony/sysbasics/tdefault.nim

`MemFile` object type in memfiles module has a `pointer` type field.
So `result = default(MemFile)` requires default for pointer.

adds default for pointer type

---

src/hexer/duplifier.nim
tests/nimony/arc/texplicit_hooks.nim

Explicit `=sink` and `=copy` are transformed to an asgn if they don't exist for a type. `derefs` will insert a haddr for the parameter of these functions, which take a `var T` parameter. We need to skip it because it is not needed for asgn

hexer: fixes explicit hooks; skipping `haddr`

---

lib/std/system/stringimpl.nim
src/hexer/stringcases.nim
src/nimony/expreval.nim
tests/nimony/casestmt/tsimple_string_case.nim

changes:
- `eval` now recursively solve the value of constants so that we don't miss suf/convs in the value of constants
- stringcases uses `nimStrAtLe` which requires a string parameter, so we need to use `borrowCStringUnsafe` from the selector

hexer: stringcases support `cstring` selectors

---

src/nimony/sem.nim
tests/nimony/errmsgs/tinvalidpragma.msgs
tests/nimony/errmsgs/tinvalidpragma.nim

follows up #988
Only process arguments if `hasParRi` is true, otherwise it is a standalone identifier and the next token would be the next pragma
Also if there are too many elements, `skipParRi` would crash the compiler, now it produces an error

proper fix for identifier pragmas, error instead of crash for too many arguments

---

src/nimony/enumtostr.nim
src/nimony/sem.nim
src/nimony/semdata.nim
tests/nimony/casestmt/tsimple_string_case.nim
tests/nimony/casestmt/tsimple_string_case.output
tests/nimony/nosystem/tbool.nif
tests/nimony/nosystem/tenumsizes.nif
tests/nimony/sets/tsets.nif
tests/nimony/sysbasics/tdollar.nif

We need to lift the `enumToStr` to the top level so that `$` can call them for local enum types (because `$` is a generic that is appended to the top level)

fixes enumToStr gen for local enum types

---

src/nimony/sem.nim
tests/nimony/when/twhenobject.nif
tests/nimony/when/twhenobject.nim

fixes #965
The same code is reused for both regular `when` statements and `when` statements inside objects, just with different endpoints for the resolved expressions. So the way of handling unresolved conditions depending on generic params etc. could be shared between the two variants when implemented.
Although the real problem is if the `when` statement is left unresolved, then expressions that iterate over the object type AST will encounter `when` trees. The fields inside them would currently be untyped as well. Nothing is done for this yet.

implement basic `when` inside object

---

src/nimony/sigmatch.nim
src/nimony/typeprops.nim
tests/nimony/generics/deps/mtypeclassmatch.nim
tests/nimony/generics/ttypeclasswrongmatch.msgs
tests/nimony/generics/ttypeclasswrongmatch.nim

follows up #931
Algorithm seems to work but I did not try every test case (cannot find much on this, [typescript](https://github.com/microsoft/TypeScript/blob/027829fbcd0a84172ab4a36d60a0ac915ca7ea09/src/compiler/checker.ts#L8467) seems to do the distributive law but not de morgan since typescript doesn't have `not` types). Since reordering can get quite slow (reordering `(and (or <M terms>) (or <N terms>)` is `O(MN)`) the typeclass is checked if it is already ordered first.
A problem with performance is the complexity of the produced terms also reflects on the complexity of the type match, `(A or B) and (C or D) and (E or F)` expands to:
```
(or
(and A C E)
(and A C F)
(and A D E)
(and A D F)
(and B C E)
(and B C F)
(and B D E)
(and B D F))
```
which performs 24 individual matches for …

implement sum of products form for typeclass matching

---

src/nimony/derefs.nim
tests/nimony/sysbasics/tdistincts.nim

`Dconv` should not affect the derefs of the original call since it doesn't do anything and is eliminated in the later phase

fixes borrowing procs with `var T`

---

src/nimony/decls.nim
src/nimony/sizeof.nim
tests/nimony/object/tcaseobject.nif
tests/nimony/object/tcaseobject.nim

fixes #1010
There are some pre-existing issues with `getSize`, which may be fixed in the following PRs. i.e.
```nim
type Foo = object
x: bool
z: string
t: bool
```
With/Without this PR, `getSize` returns `24` for this structure, while `sizeof(Foo)` returns `32` instead

implements `getSize` for case objects

---

src/hexer/nifcgen.nim
src/nimony/sem.nim
tests/nimony/ffi/cinttypedef.h
tests/nimony/ffi/deps/mimportcinttypedef.nim
tests/nimony/ffi/timportcinttypedef.nim
tests/nimony/ffi/timportcinttypedefinmod.nim

Adds header pragma to `IntT`, `UintT`, `FloatT` and `CharT` types in sem.nim when the type alias is declared with importc/importcpp and header pragma so that Hexer can add `include`.

fixes #1016

---

lib/std/system/basic_types.nim
src/nimony/sem.nim
tests/nimony/sysbasics/tprocs.nim

`InReturnTypeDecl` indicts it's a return type, not in the return type

implements `void` as return types

---

src/nimony/sigmatch.nim

https://github.com/nim-lang/nimony/pull/1018 added `HeaderP` to `IntT`, `UintT`, `FloatT` and `CharT` type nodes.
So this PR fixes sigmatch.nim to skips `HeaderP` when reading these type nodes.

sigmatch.nim skips HeaderP in IntT, UintT, FloatT and CharT type nodes

---

lib/std/parseutils.nim

refs #1023
The array is not zeroed out in nimony AFAIK, so a \0 is manually added here. Another option might be to call `zeroMem`. Passed 5 CI runs without failing.

manually insert \0 for parseutils array passed to `strtod`

---

src/nifgram/nifgram.nim

Now you can write this grammar:
```lisp
(RULE :DataValue TYP (OR STRINGLITERAL INTLIT UINTLIT FLOATLIT))
(RULE :DataKey (POP :TYP) (OR DataValue (times ".rept " INTLIT (DO "nl") DataValue (DO "nl") ".endr")) (DO "nl"))
(RULE :DataDecl SYMBOLDEF ":" (DO "nl") (STACK (ONE_OR_MANY (OR
(string ".string " DataKey)
(byte ".byte " DataKey)
(word ".short " DataKey)
(long ".long " DataKey)
(quad ".quad " DataKey)
))) (DO "nl"))
```
And this means that need to pop the DataKey from the stack, write it to the variable TYP, and then add it to stack.

nifgram: implement STACK\POP operations

---

src/hexer/vtables_backend.nim
src/nimony/sem.nim
src/nimony/sigmatch.nim
src/nimony/typeprops.nim
tests/nimony/methods/tgenericinheritance.nim
tests/nimony/methods/tgenericinheritance.output
tests/nimony/methods/tmof.nim
tests/nimony/methods/tmof.output

refs #896
Inheritance is implemented in sigmatch for `ref`/`ptr` and generic versions of object types. This is not perfectly implemented for edge cases like "generic objects matching generic objects" but should handle the most common cases fine.
Changes to vtables_backend:
* Upcasts for ref/ptr types are just `cast`s of their pointers, this works since the first field is always the parent object and makes the refcount field for `ref`s work.
* Access to the vtable field needs an upcast to the hierarchy root
* Misc fixes: Temps are fixed (leaves `(expr` open instead of immediately closing, generates `ptr` type for `addr` case), generic types do not generate unused vtables, empty methods array generates `{ NIL }` since it is a flexible array.
Leaving for followup, added to issue todo and as …

basic generic/ref inheritance

---

lib/std/system/basic_types.nim
src/hexer/vtables_backend.nim
tests/nimony/methods/deps/mgenericinheritance.nim
tests/nimony/methods/tgenericinheritance.nim
tests/nimony/methods/tmof.nim

refs #896
Not sure if there is anything else to add to system, `procCall` and `of` are already there
Cast is added to work around C compiler `const` warnings in output which are also fixed by #1053

add RootObj to system

---

src/nifc/codegen.nim
src/nifc/gentypes.nim

To prevent issues with pointer types i.e. `const int* a = ...`, now `int* const a = ...` is generated.

move `const` keyword to after type for `(const)` variables in NIFC

---

src/hexer/iterinliner.nim
src/nifler/bridge.nim
src/nimony/sem.nim

Nifler couldn't handle this case before, which enters the wrong branch for `let varTuple` instead of `for varTuple`
```nim
import std/syncio
iterator foo3(): (int, int, (int, int)) =
yield (1, 2, (3, 4))
for i, j, (m, n) in foo3():
echo i, j, m, n
```
```
(unpackflat
(let :i.0 . . 1,~4
(i -1) .)
(let 3 :j.0 . . 6,~4
(i -1) .)
(unpacktup
(let 7 :m.0 . . 12,~4
(i -1) .)
(let 10 :n.0 . . 17,~4
(i -1) .))) ~2,1
```
but removes `unpackflat` for a single `unpacktup` for convenience as before

supports mixing unpacktup and unpackflat in the front end

---

src/nimony/sem.nim
tests/nimony/sysbasics/ttuples.nim

If we don't semcheck implicit result exprs with return types, `(x: x)` is going to have the correct type of `tuple[x: var int]`, which doesn't pass `commonTypes`

semchecking implicit result exprs with return types

---

src/nimony/sem.nim
src/nimony/sembasics.nim
tests/nimony/nosystem/tresemtype.nif
tests/nimony/object/tcaseobject.nif
tests/nimony/templates/ttypedinject.nim

refs #1044 (the title, the full code in the issue needs untyped parameters to work)
`{.inject.}` in untyped templates is implemented by just generating an identifier instead of a sym, but this cannot be done in typed templates. So we accept a symbol that was generated by a template/generic and has an `{.inject.}` pragma and add it to scope again. For delayed syms this is done by just setting the status back to `OkNew` from `OkExistingFresh` so that `addSym` can define it, but another status kind like `OkExistingInject` can be added for this. For procs the symbol is manually added after pragmas, but could be done earlier with a syntactic scan for `inject` as in untyped templates.
There was an issue with enum types defined in a scope: the `$` overload for them is still generated in the top …

implement {.inject.} in typed templates

---

src/nimony/sembasics.nim

Also removes duplicated error messages.
When got undeclared identifier error, nimsem prints the identifier.

prints code that caused compile error in Nif in debug build

---

src/hexer/lifter.nim
src/hexer/vtables_backend.nim
tests/nimony/object/tmethods.nim

fixes `nimChckNilDisp` called for `var object`
fixes `getRtti` for `ptr` and `var` objects

fixes `getRtti`, inheritance and `nimChckNilDisp`

---

src/nimony/derefs.nim
src/nimony/programs.nim
src/nimony/sem.nim
src/nimony/sembasics.nim

ref https://github.com/nim-lang/nimony/issues/1066
The `error` procs have been extensively used for error reporting. In these cases below, they are actually bugs instead of errors. We can also replace existing `doAssert` usages for bug reporting with `bug` procs. It corresponds to `internalError` in Nim

improve error messages for bugs

---

src/nimony/sem.nim

I found `tests/nimony/sysbasics/tdistincts.nim` causes invalid `PackedLineInfo` in `c.dest` in `src/nimony/sem.nim`.
I added following code to check `it.n` before `addReturnResult c, resId, it.n.info` in `semBorrow` proc in `src/nimony/sem`.
```nim
assert cursorToPosition(procBody, it.n) < procBody.len
addReturnResult c, resId, it.n.info
```
That assert failed when compiled `tests/nimony/sysbasics/mdistincts.nim`:
```nim
$ ./bin/nimony c -r tests/nimony/sysbasics/mdistincts.nim 
bin/nimsem  --isMain m nimcache/mdi5tldn4.1.nif nimcache/mdi5tldn4.2.nif nimcache/mdi5tldn4.2.idx.nif
src/nimony/nimsem.nim(126) nimsem
src/nimony/nimsem.nim(123) handleCmdLine
src/nimony/nimsem.nim(54) singleModule
src/nimony/sem.nim(7341) semcheck
src/nimony/sem.nim(7289) semcheckCore
src/nimony/sem.nim(677) …
```

fixes invalid Cursor dereference

---

src/nimony/sem.nim

refs https://github.com/nim-lang/nimony/pull/1105#issuecomment-2892371137, apparently `-d:abcdef` makes `defined(abc.def)` true when it should be `-d:abc.def`

fix dotted defines deleting the dot

---

src/nimony/programs.nim
src/nimony/sem.nim
src/nimony/sembasics.nim
src/nimony/semdata.nim
tests/nimony/lookups/deps/msandwich1.nim
tests/nimony/lookups/deps/msandwich2.nim
tests/nimony/lookups/tcrossmoduleoverload.nim
tests/nimony/lookups/ttypeboundops.nim

closes #1107
Same as the implementation in original Nim, if an argument has a nominal type and the nominal type is exported from a module, the toplevel symbols of the module the type is from are scanned if they are an attachable routine to the nominal type, in which case they are considered in overload resolution.
This is done in the same place as concept procs, they are now built directly in `considerTypeboundOps` as well by iterating over `cs.args` rather than adding them when the arguments are typechecked. This is to simplify preventing symbols that were already considered in overloading from getting added, they now use the same marker set as the added typebound ops.
Apparently the position of the argument is not considered in attachment, every parameter of the routine is checked for …

argument dependent lookup

---

src/nimony/sembasics.nim
tests/nimony/errmsgs/tdistinctinfos.msgs
tests/nimony/nosystem/tdefinedarg.nif

Unlike https://github.com/nim-lang/nimony/pull/1105, when `orig` param contains error node in `buildErr` proc, use that error to avoid nest errors.
`define(abc.def)` doesn't work correctly with this PR.

don't construct nested errors in buildErr proc

---

doc/tags.md
src/hexer/nifcgen.nim
src/models/nimony_tags.nim
src/models/tags.nim
src/nimony/sem.nim
src/nimony/semdata.nim
tests/nimony/pragmas/tcustompragma.nif
tests/nimony/pragmas/tcustompragma.nim

closes #523
Custom pragmas are implemented similar to original Nim, a global table on identifiers in the sem context that doesn't care about redefinitions (though here it gets overwritten, the original compiler uses `strTableAdd` which can end up giving previous definitions). They can't have arguments so they are only invoked as standalone identifiers.
Statement pragmas are now processed as early as `SemcheckSignatures`. This is needed for custom pragmas to be used in proc signatures. Originally thought of making `assume`/`assert`/`emit` not semcheck until the bodies phase but this is not necessary since they just call `semExpr` again, they now semcheck in the signature phase just like other pragmas.

custom pragmas, process statement pragmas in signatures phase

---

src/hexer/nifcgen.nim

In `trAsNamedType` proc in `hexer/nifcgen.nim`, a type declaration for NifC is created and it is passed to `programs.publish` proc.
When `trType` proc is called with the symbol, that type declaration is passed to `asTypeDecl` proc `in nimony/decls.nim`.
But that proc assumes given type declaration is `Nim-gear2`.
As type declaration for NifC has fewer child nodes, `takeTypeDecl` proc produces invalid `Cursor`.

fixes Hexer generates invalid Cursor

---

src/nimony/nimony.nim
src/nimony/nimsem.nim

`nimsem` didn't support `--ff` flags, which are passed to it by `nimony`. It printed help messages for each module when `--ff` is used for `nimony`

documents `--ff` and adds it to nimsem to avoid help messages

---

src/hastur.nim
src/nimony/semcall.nim

The string type becomes `string.0.sysvq0asl` even with `--noSystem`, so typebound ops tries to load the system module to find its bound ops, but this fails if the system module nif file does not exist yet. So this triggered a random failure in #1145 when the nosystem category ran after nimcache was wiped. Edit: And in master now in 2dea066.
To fix this, typebound ops just ignore types from the system module, their bound ops should be in scope anyway. Nimcache is now also always deleted before the nosystem category to test that this works.

fix typebound ops with nosystem and no system module in nimcache

---

src/hexer/vtables_backend.nim
tests/nimony/object/tmethods.nim

Only lvalues can be addressed. We need to assign the expression that is not a lvalue to a temp
> if n.kind == Symbol:
A symbol has been handled already
> (addr Lvalue (cppref)?)
In nifc, it seems to require lvalues for `addr`, but it doesn't seem to check it

fixes methods: expression must be an lvalue to be addressed

---

src/nimony/semtypes.nim
tests/nimony/generics/tnestedgenericinvoke.nim

fixes #1167
Invocations track if semchecking their arguments adds to a counter of used typevar symbols, to decide if the invocation is concrete or not so that it can be instantiated. However it does this by swapping the counter with a local variable, which isolates the typevar count in the arguments from the typevar count of the invocation itself. So invocations with generic parameters do not count as generic when nested inside another invocation, which wrongly instantiates it. To fix this, the typevar counter is not isolated, only the counter changing is tracked.
Worst case `containsGenericParams` can be used on each of the arguments.

propagate used typevar count in nested invoke

---

src/nifmake/nifmake.nim

Timestamps of output files are cached before they are updated.
Even after output files are updated, nodes that uses them as input uses cached old timestamp in `needsRebuild`.

fixes #1176; when remove build artifacts, remove cached timestamp

---

lib/std/system/comparisons.nim
tests/nimony/errmsgs/tdistinctinfos.msgs
tests/nimony/iter/tforloops1.nif
tests/nimony/sysbasics/temptyseq.nif
tests/nimony/sysbasics/tintlitmatch.nif

`<` for pointers is used in src/lib/nifreader.nim.

adds `<` operator for pointers

---

src/nimony/renderer.nim
tests/nimony/plugins/trenderer.nim
tests/nimony/plugins/trenderer.output

So that `s[0]` is rendered properly

improves `renderer` for `[]` etc.

---

lib/std/system/defaults.nim

It is required to compile nifreader with Nimony.

adds default template for set[T]

---

src/nimony/semdecls.nim

`semProcBody` proc in `nimony/semdecls.nim` calls `semExpr` twice for the last expression of the proc body.
If the last expression was `[]` or `{}` and `semExpr` was called without `AllowEmpty`, `semBracket` or `semCurly` calls `buildErr` proc.
If nimsem was built with `-d:debug`, `buildErr` prints given error and quit.
If it was build without `-d:debug`, `buildErr` outputs `ErrT` node and doesnt quit. Then `semProcBody` removes that `ErrT` node and no compiler error is reported.
That is why the compile error was generated only when `-d:debug` is defined.
This PR calls `semExpr` with `AllowEmpty` in `semProcBody` so that `semBracket` or `semCurly` doesn't calls `buildErr` when they got `[]` or `{}`.

fixes #1209

---

src/hexer/duplifier.nim
tests/nimony/arc/tensuremove.nim

`[]` is a call that returns a var type, so a `deref` is needed. `(deref (call [] x))` should be moveable

fixes `ensureMove` can't move calls with var types

---

src/nimony/sem.nim
tests/nimony/sysbasics/tblocks.nim

fixes `discardable` used with `exprx`
```nim
proc test(): int {.discardable.} =
discard
block:
discard
test()
```
For discardable calls in a block statement, it gets resolved to `ExprX`. We need to transit `ExprX` to `StmtsS` for the last branch in `semStmt`, which accepts statements only

transit `ExprX` to `StmtsS` for implicitlyDiscardable

---

src/nimony/semdecls.nim

ref #1231
```nim
let s = proc (name: string): string = "Hello "
```
It becomes
```
(glet :s.0.teskvlx9c . . 9
(params 1
(param name . . 6 string .)) 9 `anonproc.0.teskvlx9c) 4,9
(proc :`anonproc.0.teskvlx9c . . .
(params 1
(param :name.0 . . 6 string.0.sysvq0asl .)) 16 string.0.sysvq0asl . . 25
(stmts
(result :result.4 . . ~18 string.0.sysvq0asl .)
(result :result.0 . . ~18 string.0.sysvq0asl .)
(asgn result.0 "Hello ") ~25
(ret result.0) ~25
(ret result.4))) 14,9
```

turns anonymous procs into normal procs

---

src/nifler/bridge.nim

nifler, given the code:
```nim
type
X = object
a: int
f: proc()
b: int
```
was producing:
```nif
(.nif24)
(.vendor "Nifler")
(.dialect "nim-parsed")
0,2,../../tmp/ntr.nim(stmts 4,1
(type ~2 X . . . 2
(object . ~2,1
(fld a . . 3 int .) ~2,2
(fld f . . 7
(proctype ....
(params) . . ..) .) ~2,3
(param b . . 3 int .))))
```
and result in the error:
```
../../tmp/ntr.nim(6, 5) Error: illformed AST inside object: 
FAILURE: /d/code/langs/nimony/bin/nifmake -j run /tmp/nimcache/ntrdan17g1.build.nif
```
(fld turned into param)

fixes fields declared after a proctype field suddenly turning into params

---

src/nimony/renderer.nim

When an incorrect type argument is passed to a procedural type parameter, nimsem calls raiseAssert.
Example code:
```nim
proc test(prc: proc ()) = prc()
test(1)
```
Error message:
```
assertions.nim(34)       raiseAssert
Error: unhandled exception: cannot happen [AssertionDefect]
```

fixes error: unhandled exception: cannot happen

---

src/nimony/sem.nim
src/nimony/semdecls.nim
tests/nimony/misc/tdo_nonation.nim

Nifler already outputs `StmtsS` from the do notation without parameters.

implements #1268; implement the do notation

---

src/nimony/sem.nim
tests/nimony/object/tcaseobject.nif
tests/nimony/object/tcaseobject2.nim

fixes #1029
picks up the first branch if nothing is selected

implements `default` for case objects

---

src/nimony/sem.nim
tests/nimony/sysbasics/tbasics2.nim

Found this problem when porting `unicode.nim` to nimony

Makes `CommentS` produces void types

---

src/hexer/nifcgen.nim
src/nifc/genexprs.nim
tests/nimony/ffi/tpacked.nim.c
tests/nimony/ffi/tunion.nim.c
tests/nimony/sysbasics/tbasics2.nim

found it when debugging `unicode.nim`. Nim does the same thing for `==`
```c
colontmpD__2 = nimBoolToStr((((NU8) s1_1) == ((NU8) 255)));
```
```c
nimcache/tesl2p8x61.c:436:15: warning: result of comparison of constant -1 with expression of type 'NC8' (aka 'unsigned char') is always false [-Wtautological-constant-out-of-range-compare]
436 |   if ((!(s1_1 == '\377'))){
|          ~~~~ ^  ~~~~~~
nimcache/tesl2p8x61.c:445:17: warning: result of comparison of constant -1 with expression of type 'NC8' (aka 'unsigned char') is always false [-Wtautological-constant-out-of-range-compare]
445 |   if ((!('\377' == s1_1))){
|          ~~~~~~ ^  ~~~~
2 warnings generated.
[Assertion Failure] 
FAILURE: nimcache/tesl2p8x61
```

fixes `==` for CharLit (Convs to NU8 needed)

---

src/lib/nifbuilder.nim

fixes `nifbuilder.nim` to output "-0.0" correctly.

fixes #1313

---

lib/std/setutils.nim
src/nimony/expreval.nim
tests/nimony/const/tconstset.nim

So I can make `const toEscapedChars = {'\32'..'\126'} - {'\\', '\'', '\"'}` work

implements more set ops for `expreval`

---

src/hexer/nifcgen.nim
tests/nimony/modules/deps/mvariables.nim
tests/nimony/modules/tvariables.nim

Set constructors are transformed in Hexer but set constructors in initial values of imported variables are not transformed and caused the error.
Hexer doesn't need to output initial values of imported variables as they are never used in NIFC.

fixes #1352; don't output initial values of imported variables

---

src/nifc/cprelude.nim
tests/nimony/ffi/tpacked.nim.c
tests/nimony/ffi/tunion.nim.c

When compiled following code, gcc generated warning:
```nim
const S = {'a' .. 'z'}
proc test(s: set[char]) = discard
test(S)
```
generated gcc warning:
```
nimcache/tes9hvujc.c: In function 'main':
nimcache/tes9hvujc.c:424:19: warning: passing argument 1 of 'test_1_tes9hvujc' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
424 | test_1_tes9hvujc((&S_0_tes9hvujc));
|                  ~^~~~~~~~~~~~~~~
nimcache/tes9hvujc.c:417:43: note: expected 'AarrayAuS8ZS32_0_t *' but argument is of type 'const AarrayAuS8ZS32_0_t *'
417 | void test_1_tes9hvujc(AarrayAuS8ZS32_0_t* s_0){
|                       ~~~~~~~~~~~~~~~~~~~~^~~
```

Suppress the warning generated when passing const sets to procedures

---

src/nimony/sem.nim
tests/nimony/pragmas/tpushpop.nif
tests/nimony/pragmas/tpushpop.nim

nimsem semchecks procedures in `SemcheckSignatures` and `SemcheckBodies` phases, but semchecks variables only in `SemcheckBodies` phase.
So makes push/pop pragma processed in both `SemcheckSignatures` and `SemcheckBodies` phases so that pushed pragmas are applied to both procedures and variables.
But pushed pragmas are added to procedures twice.

makes push/pop pragma works with variables

---

lib/std/encodings.nim

I didn't know Nimony strings are non-null terminated, probably a warning or something would be nicer

use `toCString` before passed to importc calls

---

src/hexer/nifcgen.nim
src/nimony/sem.nim
src/nimony/semcall.nim
tests/nimony/errmsgs/titerator_call_not_in_for.msgs
tests/nimony/errmsgs/titerator_call_not_in_for.nim

When the iterator matches at the call site but it is not at for statements, Nimony prints the compile error.
Also adds assert to hexer/nifcgen.nim so that it prints better error message when `trStmt` was called with `n.kind == ParRi`.

fixes #1380; calling iterators not at for statements is compile errror

---

src/hexer/constparams.nim
tests/nimony/exceptions/ttables.nim

```nim
proc `[]`*[K: Keyable, V](t: Table[K, V]; k: K): var V {.raises.} =
let idx = rawGet(t, k, hash(k))
if idx < 0:
raise KeyError
t.data[idx][1]
```
For a `var T` return type, we cannot use `getType` because it is a `var T` instead of `ptr T` returned by `getType`
```c
nimcache/ttauegnb4.c:583:12: error: assigning to 'AtupleSX45rrorX43ode0sysvq0aslAmutAiS64_0_t' (aka 'struct AtupleSX45rrorX43ode0sysvq0aslAmutAiS64_0_t') from incompatible type 'AtupleSX45rrorX43ode0sysvq0aslAptrAiS64_0_t' (aka 'struct AtupleSX45rrorX43ode0sysvq0aslAptrAiS64_0_t')
583 |   result_2 = (AtupleSX45rrorX43ode0sysvq0aslAptrAiS64_0_t){
|            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
584 |     .fld_0 = Success_0_sysvq0asl, .fld_1 = (&(*getQ_2_ttauegnb4(t_2.data_0_I8uyrpu, IL64(0))).fld_1)}
```

fixes raises with `var T`

---

src/hexer/nifcgen.nim
src/nimony/module_plugins.nim
src/nimony/sem.nim
src/nimony/semdata.nim
src/nimony/semos.nim
tests/nimony/plugins/deps/mhiddenplugin.nim
tests/nimony/plugins/deps/mlistener.nim
tests/nimony/plugins/deps/mmoduleplugin.nim
tests/nimony/plugins/deps/mtypeplugin.nim
tests/nimony/plugins/tmoduleplugin1.nim
tests/nimony/plugins/tmoduleplugin1.output
tests/nimony/plugins/tmoduleplugin2.nim
tests/nimony/plugins/tmoduleplugin2.output
tests/nimony/plugins/ttypeplugin.nim
tests/nimony/plugins/ttypeplugin.output

It searches for the plugin relative to directory the string literal originates from
so
`/dirA/a.nim`
```nim
template foo =
{.plugin: "myplugin".}
```
`/dirB/b.nim`
```nim
import ../dirA/a
foo()
```
will search for myplugin.nim in dirA (and in std)
which is what most people will probably expect it to

fixes module, type and import plugins

---

src/lib/nifindexes.nim
src/nimony/sembasics.nim
tests/nimony/modules/deps/mdont_bind_to_obj_field.nim
tests/nimony/modules/deps/mdont_bind_to_obj_field2.nim
tests/nimony/modules/tdont_bind_to_obj_field.msgs
tests/nimony/modules/tdont_bind_to_obj_field.nim
tests/nimony/modules/tdont_bind_to_obj_field2.nim

`considerImportedSymbols` proc in nimony/sembasics.nim ignores object field symbols in imported modules so that `buildSymChoice` proc never adds object field symbols to `c.dest`.

fixes #1404

---

src/nimony/pragmacanon.nim
src/nimony/sem.nim
tests/nimony/pragmas/tpushpop.nif
tests/nimony/pragmas/tpushpop.nim

Succeeds https://github.com/nim-lang/nimony/pull/1372
`CheckedPragmas` object and `isChecked` proc in nimony/pragmacanon.nim prevents duplicated pragmas.

prevents duplicated pragmas

---

doc/stdlib.dgn.md
lib/std/system.nim
tests/nimony/sysbasics/ttypeof.nim

Fixes https://github.com/nim-lang/nimony/issues/1426.
tests/nimony/sysbasics/ttypeof.nim needs https://github.com/nim-lang/nimony/pull/1430.

adds `typeof` to system module

---

doc/stdlib.dgn.md
lib/std/appdirs.nim
lib/std/paths.nim
tests/nimony/stdlib/tappdirs.nim

I got some weird issue. Some seems to be related to importing order somehow, I haven't figured the issue out yet. One is related to `inline`, I will fix it soon.
<del>
```
cycle detected: /Users/blue/Documents/GitHub/nimony/lib/std/appdirs.nim <-> /Users/blue/Documents/GitHub/nimony/lib/std/paths.nim
```
Though I don't know what is this cycle 
</del>

porting `std/appdirs` to Nimony

---

src/hexer/desugar.nim
tests/nimony/sets/tsets.nif
tests/nimony/sets/tsets.nim

fixes hexer/desugar.nim that assigned the wrong type to the temporary variable.

fixes #1459
